// This file is automatically generated

// job-Code处理器

import { JobCodeController } from '@controller'
export default {
  actions: {
    [JobCodeController.queryGluesByJobId.method]: {
      summary: 'queryGluesByJobId',
      method: 'get',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/job-code/${payload.jobId}`,
    },
    [JobCodeController.save.method]: {
      summary: 'save',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/job-code/${payload.jobId}`,
    },
  },
}
