// This file is automatically generated

// job-group处理器

import { JobGroupController } from '@controller'
export default {
  actions: {
    [JobGroupController.loadById.method]: {
      summary: 'loadById',
      method: 'get',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/job-group/${payload.id}`,
    },
    [JobGroupController.pageList.method]: {
      summary: 'pageList',
      method: 'get',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/job-group/pageList`,
    },
    [JobGroupController.remove.method]: {
      summary: 'remove',
      method: 'delete',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/job-group/${payload.id}`,
    },
    [JobGroupController.save.method]: {
      summary: 'save',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/job-group`,
    },
    [JobGroupController.update.method]: {
      summary: 'update',
      method: 'put',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/job-group`,
    },
  },
}
