// This file is automatically generated

// job-index处理器

import { JobIndexController } from '@controller'
export default {
  actions: {
    [JobIndexController.chartInfo.method]: {
      summary: 'chartInfo',
      method: 'get',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/job-index/chart-info`,
    },
  },
}
