// This file is automatically generated

// 代理管理

import { BfpAgentManagerController } from '@controller'
export default {
  actions: {
    [BfpAgentManagerController.addAgentScope.method]: {
      summary: '新增代理范围',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/api/bfp/configcenter/agent/scope`,
    },
    [BfpAgentManagerController.addFullAgentWs.method]: {
      summary: '添加完全代理',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/api/bfp/configcenter/agent/add-all-agent`,
    },
    [BfpAgentManagerController.addPartAgent1Ws.method]: {
      summary: '添加部分代理第一个页面调用接口',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/api/bfp/configcenter/agent/add-part1`,
    },
    [BfpAgentManagerController.addPartAgent2Ws.method]: {
      summary: '添加部分代理第二个页面调用接口',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/api/bfp/configcenter/agent/add-part2`,
    },
    [BfpAgentManagerController.agentDetailInfo.method]: {
      summary: '获取代理详细信息(代理人信息、委托人信息、流程信息)',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/api/bfp/configcenter/agent/detail-info`,
    },
    [BfpAgentManagerController.deleteAgentScope.method]: {
      summary: '删除代理范围',
      method: 'delete',
      apiPrefix: '/afc',
      url: (payload) => `/api/bfp/configcenter/agent/scope`,
    },
    [BfpAgentManagerController.deleteAgentWs.method]: {
      summary: '删除代理',
      method: 'delete',
      apiPrefix: '/afc',
      url: (payload) => `/api/bfp/configcenter/agent`,
    },
    [BfpAgentManagerController.modFullAgentWS.method]: {
      summary: '修改完全代理',
      method: 'put',
      apiPrefix: '/afc',
      url: (payload) => `/api/bfp/configcenter/agent/full-agent`,
    },
    [BfpAgentManagerController.modPartAgent1WS.method]: {
      summary: '修改部分代理第一个页面调用',
      method: 'put',
      apiPrefix: '/afc',
      url: (payload) => `/api/bfp/configcenter/agent/part-agent1`,
    },
    [BfpAgentManagerController.modPartAgent2WS.method]: {
      summary: '修改部分代理第二个页面调用',
      method: 'put',
      apiPrefix: '/afc',
      url: (payload) => `/api/bfp/configcenter/agent/part-agent2`,
    },
    [BfpAgentManagerController.queryAgentDetailWS.method]: {
      summary: '查询代理详情',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/api/bfp/configcenter/agent/detail`,
    },
    [BfpAgentManagerController.queryAgentScope.method]: {
      summary: '查询活动和流程',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/api/bfp/configcenter/agent/scope/all`,
    },
    [BfpAgentManagerController.queryAgentWS.method]: {
      summary: '查询代理',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/api/bfp/configcenter/agent/query`,
    },
    [BfpAgentManagerController.resetAgentScope.method]: {
      summary: '恢复默认范围',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/api/bfp/configcenter/agent/scope/rest`,
    },
    [BfpAgentManagerController.selectProcessAndActivity.method]: {
      summary: '查询活动和流程',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/api/bfp/configcenter/agent/process-and-activity`,
    },
  },
}
