// This file is automatically generated

// 代办管理

import { BfpDelegateManagerController } from '@controller'
export default {
  actions: {
    [BfpDelegateManagerController.delegateWI.method]: {
      summary: '设置代理',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/api/bfp/configcenter/delegate/site`,
    },
    [BfpDelegateManagerController.queryDelegate.method]: {
      summary: '条件查询代理',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/api/bfp/configcenter/delegate/query`,
    },
    [BfpDelegateManagerController.queryDelegateByFrom.method]: {
      summary: '通过委托人查询',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/api/bfp/configcenter/delegate/query-from`,
    },
  },
}
