// This file is automatically generated

// 流程租户管理

import { BfpMultiTenantManagerController } from '@controller'
export default {
  actions: {
    [BfpMultiTenantManagerController.addTenant.method]: {
      summary: '增加bps租户',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/api/bfp/configcenter/bps/multi-tenant/create`,
    },
    [BfpMultiTenantManagerController.deleteTenant.method]: {
      summary: '删除租户',
      method: 'delete',
      apiPrefix: '/afc',
      url: (payload) => `/api/bfp/configcenter/bps/multi-tenant/tenants`,
    },
    [BfpMultiTenantManagerController.getTenantIdentityToken.method]: {
      summary: '查询bps租户的token',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/api/bfp/configcenter/bps/multi-tenant/method`,
    },
    [BfpMultiTenantManagerController.queryAllTenants.method]: {
      summary: '查询所有bps租户',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/api/bfp/configcenter/bps/multi-tenant/tenants`,
    },
    [BfpMultiTenantManagerController.updateTenant.method]: {
      summary: '更新bps租户',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/api/bfp/configcenter/bps/multi-tenant/renew`,
    },
  },
}
