// This file is automatically generated

// 参与者日历管理

import { BfpParticipantCalendarController } from '@controller'
export default {
  actions: {
    [BfpParticipantCalendarController.deleteBizCalendar.method]: {
      summary: '删除工作日历',
      method: 'delete',
      apiPrefix: '/afc',
      url: (payload) => `/api/bfp/configcenter/participant/calendar/work/${payload.calendarId}`,
    },
    [BfpParticipantCalendarController.deleteBizCalendarList.method]: {
      summary: '批量删除工作日历',
      method: 'delete',
      apiPrefix: '/afc',
      url: (payload) => `/api/bfp/configcenter/participant/calendar/work`,
    },
    [BfpParticipantCalendarController.deleteCaleparti.method]: {
      summary: '删除参与者日历',
      method: 'delete',
      apiPrefix: '/afc',
      url: (payload) => `/api/bfp/configcenter/participant/calendar/calepartis`,
    },
    [BfpParticipantCalendarController.queryCalendarDetailsByMonth.method]: {
      summary: '查询日历明细',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/api/bfp/configcenter/participant/calendar/detail`,
    },
    [BfpParticipantCalendarController.queryCalendarList.method]: {
      summary: '查询符合条件的工作日历',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/api/bfp/configcenter/participant/calendar/list-calendar`,
    },
    [BfpParticipantCalendarController.queryCaleparti.method]: {
      summary: '根据条件查询参与者日历列表',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/api/bfp/configcenter/participant/calendar/calepartis`,
    },
    [BfpParticipantCalendarController.saveBizCalendar.method]: {
      summary: '保存工作日历',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/api/bfp/configcenter/participant/calendar/work`,
    },
    [BfpParticipantCalendarController.saveCalendarDetail.method]: {
      summary: '保存日历明细',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/api/bfp/configcenter/participant/calendar/calendar-detail`,
    },
    [BfpParticipantCalendarController.saveCaleparti.method]: {
      summary: '保存参与者日历',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/api/bfp/configcenter/participant/calendar/caleparti`,
    },
    [BfpParticipantCalendarController.selectParticipants.method]: {
      summary: '查询参与者日历树',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/api/bfp/configcenter/participant/calendar/tree`,
    },
  },
}
