// This file is automatically generated

// 流程配置中心管理

import { BfpProcessConfigController } from '@controller'
export default {
  actions: {
    [BfpProcessConfigController.deleteProcessStarter.method]: {
      summary: '删除业务流程定义的启动者权限',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/api/bfp/configcenter/configs/process/permissions/delete`,
    },
    [BfpProcessConfigController.deployProcess.method]: {
      summary: '部署流程',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/api/bfp/configcenter/configs/process/deployed-process`,
    },
    [BfpProcessConfigController.getConstantExtendAttributes.method]: {
      summary: '获取业务流程常量的扩展属性',
      method: 'get',
      apiPrefix: '/afc',
      url: (payload) => `/api/bfp/configcenter/configs/process/constant/extend`,
    },
    [BfpProcessConfigController.getExtendAttributes.method]: {
      summary: '获取业务流程和活动定义的扩展属性',
      method: 'get',
      apiPrefix: '/afc',
      url: (payload) => `/api/bfp/configcenter/configs/process/activity/extend`,
    },
    [BfpProcessConfigController.getProcessActionEvent.method]: {
      summary: '获取流程按钮事件配置',
      method: 'get',
      apiPrefix: '/afc',
      url: (payload) => `/api/bfp/configcenter/configs/process/action-event`,
    },
    [BfpProcessConfigController.getProcessActivityActions.method]: {
      summary: '获取流程活动授权操作',
      method: 'get',
      apiPrefix: '/afc',
      url: (payload) => `/api/bfp/configcenter/configs/process/activity/actions`,
    },
    [BfpProcessConfigController.getProcessActivityMessages.method]: {
      summary: '获取流程活动消息',
      method: 'get',
      apiPrefix: '/afc',
      url: (payload) => `/api/bfp/configcenter/configs/process/activity/messages`,
    },
    [BfpProcessConfigController.getProcessActivityParticipant.method]: {
      summary: '获取流程活动参与者',
      method: 'get',
      apiPrefix: '/afc',
      url: (payload) => `/api/bfp/configcenter/configs/process/activity/participants`,
    },
    [BfpProcessConfigController.getProcessDefineProperties.method]: {
      summary: '查询流程定义属性',
      method: 'get',
      apiPrefix: '/afc',
      url: (payload) => `/api/bfp/configcenter/configs/process/properties`,
    },
    [BfpProcessConfigController.getProcessGraph.method]: {
      summary: '获取流程图数据',
      method: 'get',
      apiPrefix: '/afc',
      url: (payload) => `/api/bfp/configcenter/configs/process/graph`,
    },
    [BfpProcessConfigController.getProcessStarter.method]: {
      summary: '获取业务流程定义的启动者权限',
      method: 'get',
      apiPrefix: '/afc',
      url: (payload) => `/api/bfp/configcenter/configs/process/permissions/starter`,
    },
    [BfpProcessConfigController.getStartProcessVariableContexts.method]: {
      summary: '查询流程启动变量上下文',
      method: 'get',
      apiPrefix: '/afc',
      url: (payload) => `/api/bfp/configcenter/configs/process/start-variables`,
    },
    [BfpProcessConfigController.queryActivityTimeInfoByProcessDefId.method]: {
      summary: '查询流程开启时间限制的人工活动',
      method: 'get',
      apiPrefix: '/afc',
      url: (payload) => `/api/bfp/configcenter/configs/process/manual-activity/timeinfos`,
    },
    [BfpProcessConfigController.queryAllAppInternalProcessDefs.method]: {
      summary: '根据名称查询全部应用下的流程定义',
      method: 'get',
      apiPrefix: '/afc',
      url: (payload) => `/api/bfp/configcenter/configs/process/defs`,
    },
    [BfpProcessConfigController.queryAllManualActivities.method]: {
      summary: '查询流程全部人工活动',
      method: 'get',
      apiPrefix: '/afc',
      url: (payload) => `/api/bfp/configcenter/configs/process/manual-activities`,
    },
    [BfpProcessConfigController.queryParticipantRulesByProcessDefId.method]: {
      summary: '查询流程配置的引擎级别参与者规则',
      method: 'get',
      apiPrefix: '/afc',
      url: (payload) => `/api/bfp/configcenter/configs/process/participant/rules`,
    },
    [BfpProcessConfigController.queryProcessVersions.method]: {
      summary: '查询流程定义的所有版本',
      method: 'get',
      apiPrefix: '/afc',
      url: (payload) => `/api/bfp/configcenter/configs/process/versions`,
    },
    [BfpProcessConfigController.setParticipantForActDef.method]: {
      summary: '活动定义设置引擎参与者规则',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/api/bfp/configcenter/configs/process/activity/participant/rule`,
    },
    [BfpProcessConfigController.setProcessActionEvent.method]: {
      summary: '设置流程按钮事件配置',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/api/bfp/configcenter/configs/process/action-event`,
    },
    [BfpProcessConfigController.setProcessActivityActions.method]: {
      summary: '设置流程活动授权操作',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/api/bfp/configcenter/configs/process/activity/actions`,
    },
    [BfpProcessConfigController.setProcessActivityMessages.method]: {
      summary: '设置流程活动消息',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/api/bfp/configcenter/configs/process/activity/messages`,
    },
    [BfpProcessConfigController.setProcessActivityParticipant.method]: {
      summary: '设置流程活动参与者',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/api/bfp/configcenter/configs/process/activity/participants`,
    },
    [BfpProcessConfigController.setProcessConstants.method]: {
      summary: '设置流程常量',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/api/bfp/configcenter/configs/process/constant/values`,
    },
    [BfpProcessConfigController.setProcessStarter.method]: {
      summary: '设置业务流程定义的启动者权限',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/api/bfp/configcenter/configs/process/permissions/participants`,
    },
    [BfpProcessConfigController.updateProcessDefineProperties.method]: {
      summary: '更新流程定义属性',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/api/bfp/configcenter/configs/process/properties`,
    },
  },
}
