// This file is automatically generated

// 流程汇总管理

import { BfpStatisticsManagerController } from '@controller'
export default {
  actions: {
    [BfpStatisticsManagerController.etlCollect.method]: {
      summary: '执行汇总',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/api/bfp/configcenter/statistics/collect`,
    },
    [BfpStatisticsManagerController.isInitHistroryData.method]: {
      summary: '是否需要初始化历史数据',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/api/bfp/configcenter/statistics/init`,
    },
    [BfpStatisticsManagerController.queryPersonTaskStatisticsLast7Days.method]: {
      summary: '查询员工个人流程统计数据(widget窗口)',
      method: 'get',
      apiPrefix: '/afc',
      url: (payload) => `/api/bfp/configcenter/statistics/person/week/statistic`,
    },
    [BfpStatisticsManagerController.queryTaskStatisticCount.method]: {
      summary: '查询员工个人流程统计待办、待阅、催办数量',
      method: 'get',
      apiPrefix: '/afc',
      url: (payload) => `/api/bfp/configcenter/statistics/person/quota/statistic`,
    },
    [BfpStatisticsManagerController.readEtlConfigModel.method]: {
      summary: '获取etl配置',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/api/bfp/configcenter/statistics/config`,
    },
    [BfpStatisticsManagerController.readEtlEmail.method]: {
      summary: '获取etl邮箱收件人',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/api/bfp/configcenter/statistics/email`,
    },
    [BfpStatisticsManagerController.readEtlMethod.method]: {
      summary: '获取etl汇总方法',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/api/bfp/configcenter/statistics/method`,
    },
  },
}
