// This file is automatically generated

// 工作项管理

import { BfpWorkItemManagerController } from '@controller'
export default {
  actions: {
    [BfpWorkItemManagerController.addWorkItem.method]: {
      summary: '创建工作项',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/api/bfp/configcenter/workitem`,
    },
    [BfpWorkItemManagerController.annotateWorkItem.method]: {
      summary: '批注工作项',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/api/bfp/configcenter/workitem/annotate`,
    },
    [BfpWorkItemManagerController.assignWorkItem.method]: {
      summary: '分派/领取工作项',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/api/bfp/configcenter/workitem/assign`,
    },
    [BfpWorkItemManagerController.commonQueryWorkItem.method]: {
      summary: '查询所有工作项(分页)',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/api/bfp/configcenter/workitem/all`,
    },
    [BfpWorkItemManagerController.delegateWorkItem.method]: {
      summary: '待办工作项',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/api/bfp/configcenter/workitem/delegate`,
    },
    [BfpWorkItemManagerController.deleteWorkItem.method]: {
      summary: '删除工作项',
      method: 'delete',
      apiPrefix: '/afc',
      url: (payload) => `/api/bfp/configcenter/workitem`,
    },
    [BfpWorkItemManagerController.findParticpantDetail.method]: {
      summary: '查询参与者详请',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/api/bfp/configcenter/workitem/particpant/detail`,
    },
    [BfpWorkItemManagerController.findWorkItemById.method]: {
      summary: '根据工作项id查询工作项',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/api/bfp/configcenter/workitem/by-id`,
    },
    [BfpWorkItemManagerController.finshWorkItem4ActivityInst.method]: {
      summary: '完成活动实例的工作项',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/api/bfp/configcenter/workitem/finsh-4-activity-inst`,
    },
    [BfpWorkItemManagerController.finshWorkItem4Person.method]: {
      summary: '完成工作项',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/api/bfp/configcenter/workitem/finsh-4-person`,
    },
    [BfpWorkItemManagerController.finshWorkItem4ProcessInst.method]: {
      summary: '完成流程实例的工作项',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/api/bfp/configcenter/workitem/finsh-4-process-inst`,
    },
    [BfpWorkItemManagerController.pressWorkItem.method]: {
      summary: '催办工作项',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/api/bfp/configcenter/workitem/press`,
    },
    [BfpWorkItemManagerController.queryWorkItemListByActivityInstIDWithPage.method]: {
      summary: '根据活动实例ID查询工作项(分页)',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/api/bfp/configcenter/workitem/by-activity-inst-id-with-page`,
    },
    [BfpWorkItemManagerController.queryWorkItemListByActivityInstIDWithoutPage.method]: {
      summary: '根据活动实例ID查询工作项(不分页)',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/api/bfp/configcenter/workitem/by-activity-inst-id-without-page`,
    },
    [BfpWorkItemManagerController.queryWorkItemListByProcessInstIDWithPage.method]: {
      summary: '查询某个流程实例下的所有工作项',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/api/bfp/configcenter/workitem/by-process-inst-id-with-page`,
    },
    [BfpWorkItemManagerController.reassignWorkItem.method]: {
      summary: '改派工作项',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/api/bfp/configcenter/workitem/reassign`,
    },
    [BfpWorkItemManagerController.removeWorkItem.method]: {
      summary: '移除工作项',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/api/bfp/configcenter/workitem/remove`,
    },
    [BfpWorkItemManagerController.saveWorkItem.method]: {
      summary: '保存工作项',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/api/bfp/configcenter/workitem/save`,
    },
    [BfpWorkItemManagerController.saveWorkItemFlowx.method]: {
      summary: '保存工作项并显示',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/api/bfp/configcenter/workitem/save-and-display`,
    },
  },
}
