// This file is automatically generated

// 流程中心流程定义管理

import { ProcessDefCenterController } from '@controller'
export default {
  actions: {
    [ProcessDefCenterController.createWFBizProcessDef.method]: {
      summary: '创建流程定义',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/api/bfp/configcenter/center/create-process`,
    },
    [ProcessDefCenterController.existProcessDefName.method]: {
      summary: '检查流程定义名称是否唯一',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/api/bfp/configcenter/center/exist-process`,
    },
    [ProcessDefCenterController.expandProcessDef.method]: {
      summary: '根据流程定义查询流程定义详情',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/api/bfp/configcenter/center/expand-process`,
    },
    [ProcessDefCenterController.getProcessStringByIdToJson.method]: {
      summary: '获取流程定义内容',
      method: 'get',
      apiPrefix: '/afc',
      url: (payload) => `/api/bfp/configcenter/center/def-process`,
    },
    [ProcessDefCenterController.pickupBizProcess.method]: {
      summary: '提取流程定义',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/api/bfp/configcenter/center/pickup-process`,
    },
    [ProcessDefCenterController.putinProcess.method]: {
      summary: '提交流程定义',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/api/bfp/configcenter/center/submit-process`,
    },
    [ProcessDefCenterController.queryBizProcessByName.method]: {
      summary: '通过流程定义名称获取流程临时定义基本信息',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/api/bfp/configcenter/center/name/def-process`,
    },
    [ProcessDefCenterController.submitProcessForJson.method]: {
      summary: '保存流程定义',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/api/bfp/configcenter/center/save-process`,
    },
    [ProcessDefCenterController.validateProcessForXML.method]: {
      summary: '校验流程定义',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/api/bfp/configcenter/center/validate-process`,
    },
    [ProcessDefCenterController.validateTempProcessByDefId.method]: {
      summary: '通过流程定义临时id校验流程定义',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/api/bfp/configcenter/center/validate-process/id`,
    },
  },
}
