// This file is automatically generated

// 流程实例回收管理

import { ProcessInstRecycleManageController } from '@controller'
export default {
  actions: {
    [ProcessInstRecycleManageController.deleteRecycleProcessInstBatch.method]: {
      summary: '根据回收主键删除对应数据',
      method: 'delete',
      apiPrefix: '/afc',
      url: (payload) => `/api/bfp/configcenter/processinstrecycle`,
    },
    [ProcessInstRecycleManageController.queryRecycleProcessInstList.method]: {
      summary: '条件查询被回收流程实例列表',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/api/bfp/configcenter/processinstrecycle/recycle/process-lists`,
    },
    [ProcessInstRecycleManageController.recoverProcessInst.method]: {
      summary: '恢复被回收流程实例',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/api/bfp/configcenter/processinstrecycle/recover`,
    },
  },
}
