// This file is automatically generated

// 流程实例管理

import { ProcessInstanceManageController } from '@controller'
export default {
  actions: {
    [ProcessInstanceManageController.annotateProcessInst.method]: {
      summary: '批注流程实例',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/api/bfp/configcenter/processinstance/annotate`,
    },
    [ProcessInstanceManageController.changeProcessVersionBatch.method]: {
      summary: '更换流程实例版本',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/api/bfp/configcenter/processinstance/change-version`,
    },
    [ProcessInstanceManageController.deleteProcessInstBatch.method]: {
      summary: '删除流程实例',
      method: 'delete',
      apiPrefix: '/afc',
      url: (payload) => `/api/bfp/configcenter/processinstance`,
    },
    [ProcessInstanceManageController.getAllProcessVersionList.method]: {
      summary: '通过流程定义id获取所有流程定义版本',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/api/bfp/configcenter/processinstance/all-process-version`,
    },
    [ProcessInstanceManageController.getFixedCatalogRoot.method]: {
      summary: '查询顶级业务目录树',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/api/bfp/configcenter/processinstance/top`,
    },
    [ProcessInstanceManageController.getProcessInstState.method]: {
      summary: '获取流程实例状态',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/api/bfp/configcenter/processinstance/state`,
    },
    [ProcessInstanceManageController.getProcessVersions.method]: {
      summary: '查询流程定义版本',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/api/bfp/configcenter/processinstance/process-version`,
    },
    [ProcessInstanceManageController.getRelaDataString.method]: {
      summary: '查询相关数据',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/api/bfp/configcenter/processinstance/rela-data`,
    },
    [ProcessInstanceManageController.getSubCatalogAndProcess.method]: {
      summary: '查询子业务目录及流程定义',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/api/bfp/configcenter/processinstance/sub-catalog-and-process`,
    },
    [ProcessInstanceManageController.pressProcessInst.method]: {
      summary: '催办流程实例',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/api/bfp/configcenter/processinstance/press`,
    },
    [ProcessInstanceManageController.queryProcessInstList.method]: {
      summary: '条件查询流程实例列表',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/api/bfp/configcenter/processinstance/process-lists`,
    },
    [ProcessInstanceManageController.queryProcessInstView.method]: {
      summary: '查询流程实例视图',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/api/bfp/configcenter/processinstance/process-inst-view`,
    },
    [ProcessInstanceManageController.resumeProcessInstance.method]: {
      summary: '恢复流程实例',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/api/bfp/configcenter/processinstance/resume`,
    },
    [ProcessInstanceManageController.saveRelativeData.method]: {
      summary: '保存相关数据',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/api/bfp/configcenter/processinstance/save-rela-data`,
    },
    [ProcessInstanceManageController.startProcessInstance.method]: {
      summary: '启动流程实例',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/api/bfp/configcenter/processinstance/start-process`,
    },
    [ProcessInstanceManageController.suspendProcessInst.method]: {
      summary: '挂起流程实例',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/api/bfp/configcenter/processinstance/suspend`,
    },
    [ProcessInstanceManageController.terminateProcessInstance.method]: {
      summary: '终止流程实例',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/api/bfp/configcenter/processinstance/terminate`,
    },
  },
}
