// This file is automatically generated

// groovy服务接口

import { GroovyController } from '@controller'
export default {
  actions: {
    [GroovyController.validateGroovyScript.method]: {
      summary: 'Groovy脚本语法校验',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/api/eos/groovy/actions/validate-groovy`,
    },
  },
}
