// This file is automatically generated

// 日志查看接口

import { LoggerController } from '@controller'
export default {
  actions: {
    [LoggerController.disableLog.method]: {
      summary: '取消日志记录',
      method: 'put',
      apiPrefix: '/afc',
      url: (payload) => `/api/eos/loggers/actions/disable`,
    },
    [LoggerController.enableLog.method]: {
      summary: '激活日志记录',
      method: 'put',
      apiPrefix: '/afc',
      url: (payload) => `/api/eos/loggers/actions/enable`,
    },
    [LoggerController.getLogFileNames.method]: {
      summary: '取得日志文件名称列表',
      method: 'get',
      apiPrefix: '/afc',
      url: (payload) => `/api/eos/loggers/file-names`,
    },
    [LoggerController.getLogs.method]: {
      summary: '取得日志内容',
      method: 'get',
      apiPrefix: '/afc',
      url: (payload) => `/api/eos/loggers`,
    },
  },
}
