export const model = {
  employeeCode: "",
  birthday: "",
  cardNumber: "",
  cardType: "",
  description: "",
  extra: "",
  fanNubmer: "",
  gender: null,
  hAddress: "",
  hTel: "",
  hZipcode: "",
  id: "",
  inDate: null,
  name: "",
  oAddress: "",
  oEmail: "",
  oTel: "",
  outDate: null,
  pEmail: "",
  phoneNumber: "",
  positionName: "",
  qq: "",
  remark: "",
  sortBy: "",
  status: "1",
  wechat: "",
  weibo: "",
  orgId: "",
  secretLevel:"",
  positionIds: [],
  code: "",
  password: "",
}
export const employee = {
  "id": "",
  "name": "",
  "gender": "",
  "pEmail": "",
  "birthday": "",
  "status": "",
  "cardType": "",
  "cardNumber": "",
  "inDate": null,
  "outDate": null,
  "orgId": "",
  "fanNubmer": "",
  "phoneNumber": "",
  "oTel": "",
  "oEmail": "",
  "oAddress": "",
  "hAddress": "",
  "hTel": "",
  "hZipcode": "",
  "qq": "",
  "weibo": "",
  "wechat": "",
  "description": "",
  "remark": "",
  "extra": "",
  "createTime": null,
  "updateTime": "",
  "createUser": null,
  "updateUser": "",
  "tenantId": null,
  "sortBy": 0,
  "positionName": ""
}
export const user = {
  code: "",
  password: "",
}