const inst = {
	result: {
		participants: {
			manualActivity: [
				{
					endTime: "2020-11-04 15:26:35",
					isTimeOut: "N",
					participant: "sysadmin",
					startTime: "2020-11-04 15:26:14",
				},
			],
			manualActivity11: [
				{
					endTime: "",
					isTimeOut: "N",
					participant: "Tiger",
					startTime: "2020-11-04 15:26:35",
				},
			],
			routeActivity1: [],
			startActivity: [],
		},
		states: {
			eosServiceActivity: {
				currentState: "1",
				extendAttribute: {
					activityDefID: "eosServiceActivity",
					processDefId: 1203,
				},
				height: 45,
				id: "eosServiceActivity",
				isStart: false,
				name: "用户通知",
				type: "toolapp",
				width: 64,
				x: 721,
				y: 183,
			},
			finishActivity: {
				currentState: "1",
				extendAttribute: {
					activityDefID: "finishActivity",
					processDefId: 1203,
				},
				height: 32,
				id: "finishActivity",
				isStart: false,
				name: "结束",
				type: "finish",
				width: 32,
				x: 870,
				y: 190,
			},
			manualActivity: {
				currentState: "7_0",
				extendAttribute: {
					activityDefID: "manualActivity",
					activityInstId: 5002,
					processDefId: 1203,
					processInstId: 183341,
				},
				height: 45,
				id: "manualActivity",
				isStart: false,
				name: "填写请假单",
				type: "manual",
				width: 64,
				x: 107,
				y: 272,
			},
			manualActivity1: {
				currentState: "1",
				extendAttribute: {
					activityDefID: "manualActivity1",
					processDefId: 1203,
				},
				height: 45,
				id: "manualActivity1",
				isStart: false,
				name: "部门经理审批",
				type: "manual",
				width: 64,
				x: 399,
				y: 272,
			},
			manualActivity11: {
				currentState: "2_0",
				extendAttribute: {
					activityDefID: "manualActivity11",
					activityInstId: 5004,
					processDefId: 1203,
					processInstId: 183341,
				},
				height: 45,
				id: "manualActivity11",
				isStart: false,
				name: "总裁审批",
				type: "manual",
				width: 64,
				x: 391,
				y: 89,
			},
			manualActivity12: {
				currentState: "1",
				extendAttribute: {
					activityDefID: "manualActivity12",
					processDefId: 1203,
				},
				height: 45,
				id: "manualActivity12",
				isStart: false,
				name: "人事登记",
				type: "manual",
				width: 64,
				x: 555,
				y: 183,
			},
			routeActivity1: {
				currentState: "7_0",
				extendAttribute: {
					activityDefID: "routeActivity1",
					activityInstId: 5003,
					processDefId: 1203,
					processInstId: 183341,
				},
				height: 32,
				id: "routeActivity1",
				isStart: false,
				name: "路由活动1",
				type: "route",
				width: 32,
				x: 274,
				y: 196,
			},
			startActivity: {
				currentState: "7_0",
				extendAttribute: {
					activityDefID: "startActivity",
					activityInstId: 5001,
					processDefId: 1203,
					processInstId: 183341,
				},
				height: 32,
				id: "startActivity",
				isStart: true,
				name: "开始",
				type: "start",
				width: 32,
				x: 122,
				y: 156,
			},
		},
		transCtrlBeans: [
			{
				transCtrlID: 4061,
				srcActDefName: "",
				destActDefID: "manualActivity",
				transWeight: 0,
				processInstID: 183341,
				destActDefName: "",
				lastTransTime: "20201104152614",
				srcActDefID: "startActivity",
			},
			{
				transCtrlID: 4062,
				srcActDefName: "",
				destActDefID: "routeActivity1",
				transWeight: 0,
				processInstID: 183341,
				destActDefName: "",
				lastTransTime: "20201104152635",
				srcActDefID: "manualActivity",
			},
			{
				transCtrlID: 4063,
				srcActDefName: "",
				destActDefID: "manualActivity11",
				transWeight: 0,
				processInstID: 183341,
				destActDefName: "",
				lastTransTime: "20201104152635",
				srcActDefID: "routeActivity1",
			},
		],
		transaction: [
			{
				name: "",
				extendAttribute: {},
				from: "startActivity",
				to: "manualActivity",
			},
			{
				name: "",
				extendAttribute: {},
				from: "manualActivity",
				to: "routeActivity1",
			},
			{
				name: "",
				extendAttribute: {},
				from: "manualActivity12",
				to: "eosServiceActivity",
			},
			{
				name: "请假人是经理",
				extendAttribute: {},
				from: "routeActivity1",
				to: "manualActivity11",
			},
			{
				name: "请假人不是经理",
				extendAttribute: {},
				from: "routeActivity1",
				to: "manualActivity1",
			},
			{
				name: "",
				extendAttribute: {},
				from: "manualActivity1",
				to: "manualActivity12",
			},
			{
				name: "",
				extendAttribute: {},
				from: "manualActivity11",
				to: "manualActivity12",
			},
			{
				name: "",
				extendAttribute: {},
				from: "eosServiceActivity",
				to: "finishActivity",
			},
		],
	},
};
