

import '@/components/Icon/index.js'
import './dict'
import './download-file'
import './floating-pane'
import './icon-color-picker'
import './no-data'
import './pm-dialog'
import './pm-dict'
import './pm-navigation'
// import './pm-search'
import './qr-code'
import './search-input'
import './search-remoteButton'
import './secondary-menu'
import './select-input-org'
import './select-input-user'
import './select-party'
import './select-types'
import './select-user'
import './selected-left'
import './tree-filter-input'
import './tree-list'
import './triangle-title'


