// This file is automatically generated

// bizflow

import { BizflowController } from '@controller'
export default {
  actions: {
    [BizflowController.queryUsers.method]: {
      summary: 'queryUsers',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/com.primeton.lowcode.ems.bizflow.queryUsers.biz.ext`,
    },
  },
}
