// This file is automatically generated

// cm

import { CmController } from '@controller'
export default {
  actions: {
    [CmController.ceshi.method]: {
      summary: '测试保存实体图元保存创建人id',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/com.primeton.demo.cm.ceshi.biz.ext`,
    },
    [CmController.newbiz.method]: {
      summary: 'newbiz',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/com.primeton.demo.cm.newbiz.biz.ext`,
    },
    [CmController.tel.method]: {
      summary: '手机归属地查询',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/com.primeton.demo.cm.tel.biz.ext`,
    },
  },
}
