// This file is automatically generated

// common

import { CommonController } from '@controller'
export default {
  actions: {
    [CommonController.getEntity.method]: {
      summary: '获取实体',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/com.eos.ecoding.common.getEntity.biz.ext`,
    },
    [CommonController.newbiz.method]: {
      summary: '批量保存用户信息',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/com.eos.ecoding.common.newbiz.biz.ext`,
    },
  },
}
