// This file is automatically generated

// cyxdingdan

import { CyxdingdanController } from '@controller'
export default {
  actions: {
    [CyxdingdanController.app.method]: {
      summary: '审批提交示例',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/cyxdingdan.app.biz.ext`,
    },
    [CyxdingdanController.callback.method]: {
      summary: '撤回示例',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/cyxdingdan.callback.biz.ext`,
    },
  },
}
