// This file is automatically generated

// demo1

import { Demo1Controller } from '@controller'
export default {
  actions: {
    [Demo1Controller.newbiz.method]: {
      summary: 'newbiz',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/com.primeton.gocom.lowcode.demo1.newbiz.biz.ext`,
    },
    [Demo1Controller.newbiz2.method]: {
      summary: 'newbiz',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/com.primeton.gocom.lowcode.demo1.newbiz2.biz.ext`,
    },
  },
}
