// This file is automatically generated

// demo

import { DemoController } from '@controller'
export default {
  actions: {
    [DemoController.newbiz.method]: {
      summary: 'newbiz',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/com.primeton.liujie.demo.newbiz.biz.ext`,
    },
    [DemoController.newbiz2.method]: {
      summary: 'newbiz2',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/com.primeton.liujie.demo.newbiz2.biz.ext`,
    },
  },
}
