// This file is automatically generated

// devprojectcode

import { DevprojectcodeController } from '@controller'
export default {
  actions: {
    [DevprojectcodeController.testnewbiz.method]: {
      summary: 'testnewbiz1122',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/devprojectcode.testnewbiz.biz.ext`,
    },
  },
}
