// This file is automatically generated

// digitallab

import { DigitallabController } from '@controller'
export default {
  actions: {
    [DigitallabController.persontype.method]: {
      summary: '人员类别',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/com.szewec.digitallab.persontype.biz.ext`,
    },
  },
}
