// This file is automatically generated

// ecoding

import { EcodingController } from '@controller'
export default {
  actions: {
    [EcodingController.newbiz.method]: {
      summary: '获取应用列表',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/ecoding.newbiz.biz.ext`,
    },
    [EcodingController.newbiz3.method]: {
      summary: 'newbiz3',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/ecoding.newbiz3.biz.ext`,
    },
  },
}
