// This file is automatically generated

// empdemo1028

import { Empdemo1028Controller } from '@controller'
export default {
  actions: {
    [Empdemo1028Controller.addbiz.method]: {
      summary: 'addbiz',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/empdemo1028.addbiz.biz.ext`,
    },
    [Empdemo1028Controller.deletebiz.method]: {
      summary: 'deletebiz',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/empdemo1028.deletebiz.biz.ext`,
    },
  },
}
