// This file is automatically generated

// expert

import { ExpertController } from '@controller'
export default {
  actions: {
    [ExpertController.updateJcyzt.method]: {
      summary: '修改检查员状态',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/com.iflytek.demo.expert.updateJcyzt.biz.ext`,
    },
  },
}
