// This file is automatically generated

// fff

import { FffController } from '@controller'
export default {
  actions: {
    [FffController.newbiz.method]: {
      summary: 'newbiz',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/fff.newbiz.biz.ext`,
    },
  },
}
