// This file is automatically generated

// goatman

import { GoatmanController } from '@controller'
export default {
  actions: {
    [GoatmanController.Entity.method]: {
      summary: 'Entity_create',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/goatman.Entity_create.biz.ext`,
    },
    [GoatmanController.Entity.method]: {
      summary: '删除实体服务',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/goatman.Entity_delete.biz.ext`,
    },
    [GoatmanController.Entity.method]: {
      summary: '根据ID查询实体服务',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/goatman.Entity_findById.biz.ext`,
    },
    [GoatmanController.Entity.method]: {
      summary: '分页查询实体服务',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/goatman.Entity_query.biz.ext`,
    },
    [GoatmanController.Entity.method]: {
      summary: '修改实体服务',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/goatman.Entity_update.biz.ext`,
    },
  },
}
