// This file is automatically generated

// letters

import { LettersController } from '@controller'
export default {
  actions: {
    [LettersController.ZJAddParticipant.method]: {
      summary: '转交添加参与者-copy',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/com.primeton.letters.ZJAddParticipant.biz.ext`,
    },
    [LettersController.afterCreateWorkitem.method]: {
      summary: 'newbiz',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/com.primeton.letters.afterCreateWorkitem.biz.ext`,
    },
    [LettersController.firstSubmit.method]: {
      summary: '首次提交-copy',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/com.primeton.letters.firstSubmit.biz.ext`,
    },
    [LettersController.laterSubmit.method]: {
      summary: '后续提交-copy',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/com.primeton.letters.laterSubmit.biz.ext`,
    },
    [LettersController.mock.method]: {
      summary: '验证暂存',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/com.primeton.letters.mock_save_temp.biz.ext`,
    },
    [LettersController.newbiz1.method]: {
      summary: '首次提交',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/com.primeton.letters.newbiz1.biz.ext`,
    },
    [LettersController.newbiztest.method]: {
      summary: 'test',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/com.primeton.letters.newbiztest.biz.ext`,
    },
    [LettersController.newres.method]: {
      summary: '验证添加参与者',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/com.primeton.letters.newres.biz.ext`,
    },
    [LettersController.nextSubmit.method]: {
      summary: '后续提交',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/com.primeton.letters.nextSubmit.biz.ext`,
    },
    [LettersController.qqqq.method]: {
      summary: 'qqqq',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/com.primeton.letters.qqqq.biz.ext`,
    },
    [LettersController.successUpStatus.method]: {
      summary: '审批成功修改状态',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/com.primeton.letters.successUpStatus.biz.ext`,
    },
    [LettersController.updateBohuiStatus.method]: {
      summary: '驳回时修改状态',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/com.primeton.letters.updateBohuiStatus.biz.ext`,
    },
    [LettersController.xinfangsubmit.method]: {
      summary: '信访申请提交保存',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/com.primeton.letters.xinfangsubmit.biz.ext`,
    },
  },
}
