// This file is automatically generated

// licy_test

import { Licy_testController } from '@controller'
export default {
  actions: {
    [Licy_testController.licy.method]: {
      summary: 'newbiz',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/licy_test.newbiz.biz.ext`,
    },
    [Licy_testController.licy.method]: {
      summary: 'newbiz',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/licy_test.newbiz11.biz.ext`,
    },
  },
}
