// This file is automatically generated

// liujie

import { LiujieController } from '@controller'
export default {
  actions: {
    [LiujieController.demoResource.method]: {
      summary: 'demoResource1111222',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/com.primeton.liujie.demoResource.biz.ext`,
    },
    [LiujieController.demoResourceFileid.method]: {
      summary: 'demoResourceFileid',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/com.primeton.liujie.demoResourceFileid.biz.ext`,
    },
    [LiujieController.engine.method]: {
      summary: 'engine_test',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/com.primeton.liujie.engine_test.biz.ext`,
    },
    [LiujieController.flow3.method]: {
      summary: '流程测试事件3',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/com.primeton.liujie.flow3.biz.ext`,
    },
    [LiujieController.flowbiz4.method]: {
      summary: 'flowbiz4',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/com.primeton.liujie.flowbiz4.biz.ext`,
    },
  },
}
