// This file is automatically generated

// newcomponent

import { NewcomponentController } from '@controller'
export default {
  actions: {
    [NewcomponentController.testbiz.method]: {
      summary: '登录',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/com.primeton.gocom.afcenter.demo.newcomponent.testbiz.biz.ext`,
    },
  },
}
