// This file is automatically generated

// order_test

import { Order_testController } from '@controller'
export default {
  actions: {
    [Order_testController.order.method]: {
      summary: '审批',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/order_test.approvetest.biz.ext`,
    },
    [Order_testController.order.method]: {
      summary: '撤回',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/order_test.recalltest.biz.ext`,
    },
  },
}
