// This file is automatically generated

// orderdata

import { OrderdataController } from '@controller'
export default {
  actions: {
    [OrderdataController.entity.method]: {
      summary: '新增实体服务',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/orderdata.entity_create.biz.ext`,
    },
    [OrderdataController.entity.method]: {
      summary: '删除实体服务',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/orderdata.entity_delete.biz.ext`,
    },
    [OrderdataController.entity.method]: {
      summary: '根据ID查询实体服务',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/orderdata.entity_findById.biz.ext`,
    },
    [OrderdataController.entity.method]: {
      summary: '分页查询实体服务',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/orderdata.entity_query.biz.ext`,
    },
    [OrderdataController.entity.method]: {
      summary: '修改实体服务',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/orderdata.entity_update.biz.ext`,
    },
    [OrderdataController.order.method]: {
      summary: '审批提交',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/orderdata.order.biz.ext`,
    },
    [OrderdataController.recalltest.method]: {
      summary: '撤回示例',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/orderdata.recalltest.biz.ext`,
    },
  },
}
