// This file is automatically generated

// safeNewsIssue

import { SafenewsissueController } from '@controller'
export default {
  actions: {
    [SafenewsissueController.writeInStudents.method]: {
      summary: '写入学员',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/safeNewsIssue.writeInStudents.biz.ext`,
    },
  },
}
