// This file is automatically generated

// summer

import { SummerController } from '@controller'
export default {
  actions: {
    [SummerController.newbiz.method]: {
      summary: 'newbiz',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/summer.newbiz.biz.ext`,
    },
  },
}
