// This file is automatically generated

// test

import { TestController } from '@controller'
export default {
  actions: {
    [TestController.newbiz3.method]: {
      summary: '实体服务测试',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/com.test.newbiz3.biz.ext`,
    },
    [TestController.newbiz4.method]: {
      summary: '流程模板',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/com.test.newbiz4.biz.ext`,
    },
    [TestController.teacher.method]: {
      summary: '批量删除实体服务',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/test.teacher_batchDelete.biz.ext`,
    },
    [TestController.teacher.method]: {
      summary: '批量查询实体服务',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/test.teacher_batchSearch.biz.ext`,
    },
    [TestController.teacher.method]: {
      summary: 'teacher_create',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/test.teacher_create.biz.ext`,
    },
    [TestController.teacher.method]: {
      summary: 'teacher_delete',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/test.teacher_delete.biz.ext`,
    },
    [TestController.teacher.method]: {
      summary: 'teacher_findById',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/test.teacher_findById.biz.ext`,
    },
    [TestController.teacher.method]: {
      summary: 'teacher_query',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/test.teacher_query.biz.ext`,
    },
    [TestController.teacher.method]: {
      summary: 'teacher_update',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/test.teacher_update.biz.ext`,
    },
  },
}
