// This file is automatically generated

// ton0309

import { Ton0309Controller } from '@controller'
export default {
  actions: {
    [Ton0309Controller.newbiz.method]: {
      summary: 'newbiz',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/ton0309.newbiz.biz.ext`,
    },
  },
}
