// This file is automatically generated

// ton0110

import { Ton0110Controller } from '@controller'
export default {
  actions: {
    [Ton0110Controller.Entity.method]: {
      summary: '新增实体服务',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/ton0110.Entity_create.biz.ext`,
    },
    [Ton0110Controller.Entity.method]: {
      summary: '删除实体服务',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/ton0110.Entity_delete.biz.ext`,
    },
    [Ton0110Controller.Entity.method]: {
      summary: '根据ID查询实体服务',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/ton0110.Entity_findById.biz.ext`,
    },
    [Ton0110Controller.Entity.method]: {
      summary: '分页查询实体服务',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/ton0110.Entity_query.biz.ext`,
    },
    [Ton0110Controller.Entity.method]: {
      summary: '修改实体服务',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/ton0110.Entity_update.biz.ext`,
    },
    [Ton0110Controller.newbiz.method]: {
      summary: 'newbiz',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/ton0110.newbiz.biz.ext`,
    },
    [Ton0110Controller.onApprove.method]: {
      summary: '审批通过',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/ton0110.onApprove.biz.ext`,
    },
    [Ton0110Controller.onDrawback.method]: {
      summary: '审批通过后撤回',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/ton0110.onDrawback.biz.ext`,
    },
    [Ton0110Controller.testEntity.method]: {
      summary: '新增实体服务',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/ton0110.testEntity_create.biz.ext`,
    },
    [Ton0110Controller.testEntity.method]: {
      summary: '删除实体服务',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/ton0110.testEntity_delete.biz.ext`,
    },
    [Ton0110Controller.testEntity.method]: {
      summary: '根据ID查询实体服务',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/ton0110.testEntity_findById.biz.ext`,
    },
    [Ton0110Controller.testEntity.method]: {
      summary: '分页查询实体服务',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/ton0110.testEntity_query.biz.ext`,
    },
    [Ton0110Controller.testEntity.method]: {
      summary: '修改实体服务',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/ton0110.testEntity_update.biz.ext`,
    },
  },
}
