// This file is automatically generated

// ton315

import { Ton315Controller } from '@controller'
export default {
  actions: {
    [Ton315Controller.entity.method]: {
      summary: '新增实体服务',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/ton315.entity_create.biz.ext`,
    },
    [Ton315Controller.entity.method]: {
      summary: '删除实体服务',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/ton315.entity_delete.biz.ext`,
    },
    [Ton315Controller.entity.method]: {
      summary: '根据ID查询实体服务',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/ton315.entity_findById.biz.ext`,
    },
    [Ton315Controller.entity.method]: {
      summary: '分页查询实体服务',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/ton315.entity_query.biz.ext`,
    },
    [Ton315Controller.entity.method]: {
      summary: '修改实体服务',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/ton315.entity_update.biz.ext`,
    },
  },
}
