// This file is automatically generated

// UI

import { UiController } from '@controller'
export default {
  actions: {
    [UiController.newbiz.method]: {
      summary: 'newbiz',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/UI.newbiz.biz.ext`,
    },
    [UiController.newbiz2.method]: {
      summary: 'newbiz2',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/UI.newbiz2.biz.ext`,
    },
    [UiController.newbiz3.method]: {
      summary: 'newbiz3',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/UI.newbiz3.biz.ext`,
    },
  },
}
