// This file is automatically generated

// wangbl

import { WangblController } from '@controller'
export default {
  actions: {
    [WangblController.newbiz.method]: {
      summary: 'newbiz',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/wangbl.newbiz.biz.ext`,
    },
  },
}
