// This file is automatically generated

// wuyh

import { WuyhController } from '@controller'
export default {
  actions: {
    [WuyhController.newbiz.method]: {
      summary: 'newbiz',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/com.primeton.wuyh.newbiz.biz.ext`,
    },
  },
}
