// This file is automatically generated

// wy0214

import { Wy0214Controller } from '@controller'
export default {
  actions: {
    [Wy0214Controller.newbiz.method]: {
      summary: 'newbiz',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/wy0214.newbiz.biz.ext`,
    },
  },
}
