// This file is automatically generated

// wy0302

import { Wy0302Controller } from '@controller'
export default {
  actions: {
    [Wy0302Controller.newbiz.method]: {
      summary: 'newbiz',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/wy0302.newbiz.biz.ext`,
    },
  },
}
