// This file is automatically generated

// wy0730

import { Wy0730Controller } from '@controller'
export default {
  actions: {
    [Wy0730Controller.Entity.method]: {
      summary: '新增实体服务',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/wy0730.Entity_create.biz.ext`,
    },
    [Wy0730Controller.Entity.method]: {
      summary: '删除实体服务',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/wy0730.Entity_delete.biz.ext`,
    },
    [Wy0730Controller.Entity.method]: {
      summary: '根据ID查询实体服务',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/wy0730.Entity_findById.biz.ext`,
    },
    [Wy0730Controller.Entity.method]: {
      summary: '分页查询实体服务',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/wy0730.Entity_query.biz.ext`,
    },
    [Wy0730Controller.Entity.method]: {
      summary: '修改实体服务',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/wy0730.Entity_update.biz.ext`,
    },
    [Wy0730Controller.wy0730.method]: {
      summary: '新增实体服务',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/wy0730.wy0730_create.biz.ext`,
    },
    [Wy0730Controller.wy0730.method]: {
      summary: '删除实体服务',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/wy0730.wy0730_delete.biz.ext`,
    },
    [Wy0730Controller.wy0730.method]: {
      summary: '根据ID查询实体服务',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/wy0730.wy0730_findById.biz.ext`,
    },
    [Wy0730Controller.wy0730.method]: {
      summary: '分页查询实体服务',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/wy0730.wy0730_query.biz.ext`,
    },
    [Wy0730Controller.wy0730.method]: {
      summary: '修改实体服务',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/wy0730.wy0730_update.biz.ext`,
    },
  },
}
