// This file is automatically generated

// xifanzhou

import { XifanzhouController } from '@controller'
export default {
  actions: {
    [XifanzhouController.newbiz.method]: {
      summary: 'newbiz',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/xifanzhou.newbiz.biz.ext`,
    },
    [XifanzhouController.newbiz1.method]: {
      summary: 'newbiz',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/xifanzhou.newbiz1.biz.ext`,
    },
    [XifanzhouController.newbiz1111111111.method]: {
      summary: 'newbiz',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/xifanzhou.newbiz1111111111.biz.ext`,
    },
    [XifanzhouController.newbiz2.method]: {
      summary: 'newbiz2',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/xifanzhou.newbiz2.biz.ext`,
    },
    [XifanzhouController.newbiz3.method]: {
      summary: 'newbiz4',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/xifanzhou.newbiz3.biz.ext`,
    },
  },
}
