// This file is automatically generated

// xifanTest

import { XifantestController } from '@controller'
export default {
  actions: {
    [XifantestController.newbiz.method]: {
      summary: 'newbiz',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/xifanTest.newbiz.biz.ext`,
    },
    [XifantestController.newbiz222.method]: {
      summary: 'newbiz',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/xifanTest.newbiz222.biz.ext`,
    },
  },
}
