// This file is automatically generated

// yang

import { YangController } from '@controller'
export default {
  actions: {
    [YangController.newbizas.method]: {
      summary: 'newbizas',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/yang.newbizas.biz.ext`,
    },
  },
}
