// This file is automatically generated

// yuan_test

import { Yuan_testController } from '@controller'
export default {
  actions: {
    [Yuan_testController.yuan.method]: {
      summary: '新增实体服务',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/yuan_test.Entity_create.biz.ext`,
    },
    [Yuan_testController.yuan.method]: {
      summary: '删除实体服务',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/yuan_test.Entity_delete.biz.ext`,
    },
    [Yuan_testController.yuan.method]: {
      summary: '根据ID查询实体服务',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/yuan_test.Entity_findById.biz.ext`,
    },
    [Yuan_testController.yuan.method]: {
      summary: '分页查询实体服务',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/yuan_test.Entity_query.biz.ext`,
    },
    [Yuan_testController.yuan.method]: {
      summary: '修改实体服务',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/yuan_test.Entity_update.biz.ext`,
    },
    [Yuan_testController.yuan.method]: {
      summary: 'newbiz',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/yuan_test.newbiz.biz.ext`,
    },
  },
}
