// This file is automatically generated

// zhaoel

import { ZhaoelController } from '@controller'
export default {
  actions: {
    [ZhaoelController.newbiz.method]: {
      summary: 'newbiz',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/zhaoel.newbiz.biz.ext`,
    },
    [ZhaoelController.newbiz11212.method]: {
      summary: '张撒啊啊',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/zhaoel.newbiz11212.biz.ext`,
    },
    [ZhaoelController.newbizaaaa.method]: {
      summary: 'newbizaaaaaaa',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/zhaoel.newbizaaaa.biz.ext`,
    },
    [ZhaoelController.newbizaaaaa.method]: {
      summary: 'newbizaaaaaa',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/zhaoel.newbizaaaaa.biz.ext`,
    },
    [ZhaoelController.newbizasxds.method]: {
      summary: 'newbizssa',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/zhaoel.newbizasxds.biz.ext`,
    },
    [ZhaoelController.newbizces.method]: {
      summary: 'newbizces',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/zhaoel.newbizces.biz.ext`,
    },
  },
}
