// This file is automatically generated

// {{tags}}

import { {{model}} } from '@controller'
export default {
  actions: {
    {{#list}}
    [{{this.model}}.{{this.action}}.method]: {
      summary: '{{this.summary}}',
      method: '{{this.method}}',
      apiPrefix: {{this.apiPrefix}},
      url: (payload) => `{{this.url}}`,
    },
    {{/list}}
  },
}
