// This file is automatically generated

// 分析数据源和应用的关系管理

import { AppBiDatasourceController } from '@controller'
export default {
  actions: {
    [AppBiDatasourceController.create.method]: {
      summary: '新增分析数据源和应用的关系',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/app-bi-datasources`,
    },
    [AppBiDatasourceController.deleteByIds.method]: {
      summary: '按主键集合删除(参数放body)',
      method: 'put',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/app-bi-datasources/bulk-delete`,
    },
    [AppBiDatasourceController.queryApplicationBiDatasources.method]: {
      summary: '分页查询分析数据源和应用的关系列表',
      method: 'get',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/app-bi-datasources`,
    },
    [AppBiDatasourceController.update.method]: {
      summary: '修改分析数据源和应用的关系',
      method: 'put',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/app-bi-datasources`,
    },
  },
}
