// This file is automatically generated

// BI访问凭证获取

import { BiApiTokenController } from '@controller'
export default {
  actions: {
    [BiApiTokenController.getBIToken.method]: {
      summary: '通过应用编码查询BI凭证',
      method: 'get',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/bi-api-token`,
    },
  },
}
