// This file is automatically generated

// 业务对象管理

import { BusinessObjectController } from '@controller'
export default {
  actions: {
    [BusinessObjectController.create.method]: {
      summary: '新增业务对象',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/business-objects`,
    },
    [BusinessObjectController.deleteByIds.method]: {
      summary: '按主键集合删除(参数放body)',
      method: 'put',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/business-objects/bulk-delete`,
    },
    [BusinessObjectController.findBusinessObject.method]: {
      summary: '根据id查询',
      method: 'get',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/business-objects/${payload.id}`,
    },
    [BusinessObjectController.findBusinessObjectByCode.method]: {
      summary: '根据CODE查询',
      method: 'get',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/business-objects/action/${payload.code}/get-by-code`,
    },
    [BusinessObjectController.isExist.method]: {
      summary: '校验code是否重复',
      method: 'get',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/business-objects/exist/${payload.code}/${payload.tenantId}`,
    },
    [BusinessObjectController.queryBusinessObjectsByCriteria.method]: {
      summary: '分页查询业务对象列表',
      method: 'get',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/business-objects`,
    },
    [BusinessObjectController.update.method]: {
      summary: '修改业务对象-基础信息',
      method: 'put',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/business-objects`,
    },
  },
}
