// This file is automatically generated

// 组件中心管理

import { ComponentCenterController } from '@controller'
export default {
  actions: {
    [ComponentCenterController.deletes.method]: {
      summary: '按主键删除组件分组(支持批量删除)',
      method: 'delete',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/component-centers`,
    },
    [ComponentCenterController.download.method]: {
      summary: '下载组件库包',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/component-centers/actions/download`,
    },
    [ComponentCenterController.existenceByCode.method]: {
      summary: '校验code是否存在',
      method: 'get',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/component-centers/${payload.code}/exist`,
    },
    [ComponentCenterController.export.method]: {
      summary: '导出组件库',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/component-centers/actions/export`,
    },
    [ComponentCenterController.get.method]: {
      summary: '按id或者code查询当前正在使用的组件库信息',
      method: 'get',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/component-centers/${payload.id}`,
    },
    [ComponentCenterController.importComponents.method]: {
      summary: '导入组件库',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/component-centers/actions/import`,
    },
    [ComponentCenterController.queryWithPage.method]: {
      summary: '分页查询组件库列表',
      method: 'get',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/component-centers`,
    },
    [ComponentCenterController.updateBasicInfo.method]: {
      summary: '修改基本信息',
      method: 'put',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/component-centers/${payload.id}/basic`,
    },
    [ComponentCenterController.upload.method]: {
      summary: '上传组件库zip包',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/component-centers/actions/upload`,
    },
  },
}
