// This file is automatically generated

// xxx测试

import { DemoController2 } from '@controller'
export default {
  actions: {
    [DemoController2.test44.method]: {
      summary: 'test44',
      method: 'get',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/demos/${payload.name}/exclude.bb`,
    },
    [DemoController2.test55.method]: {
      summary: 'test55',
      method: 'get',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/demos/logs/exclude.dd`,
    },
    [DemoController2.testImpo.method]: {
      summary: 'testImpo',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/demos/logs-import`,
    },
    [DemoController2.testLog.method]: {
      summary: 'testLog',
      method: 'get',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/demos/logs`,
    },
    [DemoController2.testPath.method]: {
      summary: 'testPath',
      method: 'get',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/demos/path/${payload.name}`,
    },
  },
}
