// This file is automatically generated

// 开发中心管理

import { DevelopCenterController } from '@controller'
export default {
  actions: {
    [DevelopCenterController.createApp.method]: {
      summary: '创建应用',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/dev-centers/apps`,
    },
    [DevelopCenterController.createRuntimeResource.method]: {
      summary: '添加资源(包括操作系统和数据库)',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/dev-centers/runtime-resources`,
    },
    [DevelopCenterController.deleteApp.method]: {
      summary: '删除应用',
      method: 'delete',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/dev-centers/apps/${payload.appCode}`,
    },
    [DevelopCenterController.deleteRuntimeResource.method]: {
      summary: '删除资源信息',
      method: 'delete',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/dev-centers/runtime-resources`,
    },
    [DevelopCenterController.queryAppPorts.method]: {
      summary: '查询当前系统可用的应用端口列表',
      method: 'get',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/dev-centers/apps/ports`,
    },
    [DevelopCenterController.queryRuntimeResourcesWithPage.method]: {
      summary: '分页查询运行资源列表(包括操作系统和数据库)',
      method: 'get',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/dev-centers/runtime-resources`,
    },
    [DevelopCenterController.reDeployApp.method]: {
      summary: '重新部署应用(支持修改应用端口、资源等)',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/dev-centers/apps/${payload.appCode}/reDeploy`,
    },
    [DevelopCenterController.rename.method]: {
      summary: '修改应用基本信息(显示名称和描述、负责人等)',
      method: 'put',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/dev-centers/apps/rename/${payload.appCode}`,
    },
    [DevelopCenterController.showdownApp.method]: {
      summary: '停止应用',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/dev-centers/apps/${payload.appCode}/showdown`,
    },
    [DevelopCenterController.startUpApp.method]: {
      summary: '启用应用',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/dev-centers/apps/${payload.appCode}/startup`,
    },
    [DevelopCenterController.testConnection.method]: {
      summary: '数据资源连接测试',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/dev-centers/test-connect`,
    },
    [DevelopCenterController.updateRuntimeResource.method]: {
      summary: '修改资源信息',
      method: 'put',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/dev-centers/runtime-resources`,
    },
    [DevelopCenterController.verifyAddress.method]: {
      summary: '校验资源ip、port可用性(true:已被占用;false:可用)',
      method: 'get',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/dev-centers/verify-address`,
    },
    [DevelopCenterController.verifyMemoryWithCreateApp.method]: {
      summary: '创建应用时校验内存',
      method: 'get',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/dev-centers/apps/verify-memory`,
    },
  },
}
