// This file is automatically generated

// 字典类型管理

import { DictTypeController } from '@controller'
export default {
  actions: {
    [DictTypeController.create.method]: {
      summary: '新增字典类型',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/dict-types`,
    },
    [DictTypeController.createBatchWithCascade.method]: {
      summary: '新增字典类型(批量保存-支持级联保存字典项)',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/dict-types/cascade`,
    },
    [DictTypeController.deleteByIds.method]: {
      summary: '根据主键批量删除字典类型',
      method: 'delete',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/dict-types`,
    },
    [DictTypeController.downloadDictTemplate.method]: {
      summary: '字典模板下载',
      method: 'get',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/dict-types/download-dict-template`,
    },
    [DictTypeController.exportDictTypes.method]: {
      summary: '字典类型导出',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/dict-types/export-dict`,
    },
    [DictTypeController.findDictTypeIsExist.method]: {
      summary: '校验指定租户下是否存在字典类型编码或字典类型名称，true存在',
      method: 'get',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/dict-types/exist`,
    },
    [DictTypeController.getDictTypeById.method]: {
      summary: '根据id查询字典类型',
      method: 'get',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/dict-types/${payload.id}`,
    },
    [DictTypeController.importDict.method]: {
      summary: '字典导入',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/dict-types/${payload.importSetting}/import-dict`,
    },
    [DictTypeController.queryDictTypesByCriteria.method]: {
      summary: '条件查询字典类型,分页展示',
      method: 'get',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/dict-types`,
    },
    [DictTypeController.queryDictTypesByParentId.method]: {
      summary: '通过字典类型id查找字典类型子级列表',
      method: 'get',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/dict-types/${payload.parentId}/childs`,
    },
    [DictTypeController.update.method]: {
      summary: '修改字典类型',
      method: 'put',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/dict-types`,
    },
  },
}
