// This file is automatically generated

// 字典项管理

import { DictEntryController } from '@controller'
export default {
  actions: {
    [DictEntryController.create.method]: {
      summary: '新增字典项',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/dict-entries`,
    },
    [DictEntryController.deleteByIds.method]: {
      summary: '根据主键批量删除字典项',
      method: 'delete',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/dict-entries`,
    },
    [DictEntryController.findDictEntryIsExist.method]: {
      summary: '校验是否存在字典项编码或字典项名称，true存在',
      method: 'get',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/dict-entries/exist`,
    },
    [DictEntryController.getDictEntityByCode.method]: {
      summary: '根据字典项CODE查询字典项',
      method: 'get',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/dict-entries/code/${payload.code}`,
    },
    [DictEntryController.getDictEntityById.method]: {
      summary: '根据字典项ID查询字典项',
      method: 'get',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/dict-entries/${payload.id}`,
    },
    [DictEntryController.queryDictEntrysByCriteria.method]: {
      summary: '条件查询字典项,分页展示',
      method: 'get',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/dict-entries`,
    },
    [DictEntryController.queryDictEntrysByDictTypeId.method]: {
      summary: '通过字典类型ID查找字典项',
      method: 'get',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/dict-entries/${payload.dictTypeId}/dicts`,
    },
    [DictEntryController.queryDictEntrysByDictTypeIds.method]: {
      summary: '通过字典类型IDS批量查找字典项',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/dict-entries/dicts`,
    },
    [DictEntryController.update.method]: {
      summary: '修改字典项',
      method: 'put',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/dict-entries`,
    },
  },
}
