// This file is automatically generated

// 维度管理

import { DimensionController } from '@controller'
export default {
  actions: {
    [DimensionController.create.method]: {
      summary: '新增维度',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/dimensions`,
    },
    [DimensionController.deleteByIds.method]: {
      summary: '根据主键集合批量删除维度',
      method: 'delete',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/dimensions`,
    },
    [DimensionController.findDimensionIsExist.method]: {
      summary: '校验当前租户下是否存在维度code或维度名称，true存在',
      method: 'get',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/dimensions/exist`,
    },
    [DimensionController.getDimensionByCode.method]: {
      summary: '根据code查询维度',
      method: 'get',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/dimensions/${payload.code}/info`,
    },
    [DimensionController.getDimensionById.method]: {
      summary: '根据id查询维度',
      method: 'get',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/dimensions/info/${payload.id}`,
    },
    [DimensionController.queryDimensionsWithPage.method]: {
      summary: '条件查询维度列表,分页展示,排序',
      method: 'get',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/dimensions`,
    },
    [DimensionController.update.method]: {
      summary: '修改维度信息',
      method: 'put',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/dimensions`,
    },
  },
}
