// This file is automatically generated

// 功能码工具管理

import { FunctionCodeToolsController } from '@controller'
export default {
  actions: {
    [FunctionCodeToolsController.downloadResourceTemplate.method]: {
      summary: '应用资源模板下载',
      method: 'get',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/function-code-tools/download-resource-template`,
    },
    [FunctionCodeToolsController.exportAppResources.method]: {
      summary: '应用资源导出excel',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/function-code-tools/${payload.appId}/${payload.resType}/export-app-resources`,
    },
    [FunctionCodeToolsController.exportFunctionCodes.method]: {
      summary: '功能码导出',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/function-code-tools/${payload.appId}/${payload.state}/export-function-codes`,
    },
    [FunctionCodeToolsController.importAppResources.method]: {
      summary: '应用资源导入',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/function-code-tools/${payload.importSetting}/import-app-resource`,
    },
    [FunctionCodeToolsController.importFromFile.method]: {
      summary: '从文件导入(暂时不用)',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/function-code-tools/${payload.appId}/import-from-file`,
    },
    [FunctionCodeToolsController.importFromUrl.method]: {
      summary: '从URL导入(暂时不用)',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/function-code-tools/${payload.appId}/import-from-url`,
    },
    [FunctionCodeToolsController.importFunCodesFromFIleOrUrl.method]: {
      summary: '根据上传文件(优先)或者指定URL导入功能码(优先用这个接口)',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/function-code-tools/${payload.appId}/import-function-codes`,
    },
    [FunctionCodeToolsController.parseFunCodes.method]: {
      summary: '根据上传文件(优先)或者指定URL解析功能码(老接口)',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/function-code-tools/${payload.appId}/parse-function-codes`,
    },
    [FunctionCodeToolsController.parseFunCodesByFile.method]: {
      summary: '根据上传文件或指定资源类型解析功能码(新接口)',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/function-code-tools/${payload.appId}/parse-function-codes-by-file`,
    },
  },
}
