// This file is automatically generated

// 国际化处理器

import { GeneralI18nController } from '@controller'
export default {
  actions: {
    [GeneralI18nController.delete.method]: {
      summary: '删除国际化信息(支持批量删除)',
      method: 'delete',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/i18ns`,
    },
    [GeneralI18nController.downloadI18nTemplate.method]: {
      summary: '国际化模板下载',
      method: 'get',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/i18ns/actions/download-i18n-template`,
    },
    [GeneralI18nController.exportI18nMessages.method]: {
      summary: '国际化信息导出',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/i18ns/actions/export`,
    },
    [GeneralI18nController.importI18nMessages.method]: {
      summary: '国际化信息导入',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/i18ns/actions/${payload.importSetting}/import`,
    },
    [GeneralI18nController.queryWithPage.method]: {
      summary: '分页条件查询国际化信息列表',
      method: 'get',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/i18ns`,
    },
    [GeneralI18nController.save.method]: {
      summary: '保存国际化信息(支持批量)',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/i18ns`,
    },
  },
}
