// This file is automatically generated

// 组件管理

import { LowcodeComponentResourceController } from '@controller'
export default {
  actions: {
    [LowcodeComponentResourceController.getStaticResource.method]: {
      summary: '获取资源:一级目录',
      method: 'get',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/components/${payload.componentCode}/${payload.path}`,
    },
    [LowcodeComponentResourceController.getStaticResource10.method]: {
      summary: '获取资源：十级目录',
      method: 'get',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/components/${payload.componentCode}/${payload.path1}/${payload.path2}/${payload.path3}/${payload.path4}/${payload.path5}/${payload.path6}/${payload.path7}/${payload.path8}/${payload.path9}/${payload.path10}`,
    },
    [LowcodeComponentResourceController.getStaticResource2.method]: {
      summary: '获取资源：二级目录',
      method: 'get',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/components/${payload.componentCode}/${payload.path1}/${payload.path2}`,
    },
    [LowcodeComponentResourceController.getStaticResource3.method]: {
      summary: '获取资源：三级目录',
      method: 'get',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/components/${payload.componentCode}/${payload.path1}/${payload.path2}/${payload.path3}`,
    },
    [LowcodeComponentResourceController.getStaticResource4.method]: {
      summary: '获取资源：四级目录',
      method: 'get',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/components/${payload.componentCode}/${payload.path1}/${payload.path2}/${payload.path3}/${payload.path4}`,
    },
    [LowcodeComponentResourceController.getStaticResource5.method]: {
      summary: '获取资源：五级目录',
      method: 'get',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/components/${payload.componentCode}/${payload.path1}/${payload.path2}/${payload.path3}/${payload.path4}/${payload.path5}`,
    },
    [LowcodeComponentResourceController.getStaticResource6.method]: {
      summary: '获取资源：六级目录',
      method: 'get',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/components/${payload.componentCode}/${payload.path1}/${payload.path2}/${payload.path3}/${payload.path4}/${payload.path5}/${payload.path6}`,
    },
    [LowcodeComponentResourceController.getStaticResource7.method]: {
      summary: '获取资源：七级目录',
      method: 'get',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/components/${payload.componentCode}/${payload.path1}/${payload.path2}/${payload.path3}/${payload.path4}/${payload.path5}/${payload.path6}/${payload.path7}`,
    },
    [LowcodeComponentResourceController.getStaticResource8.method]: {
      summary: '获取资源：八级目录',
      method: 'get',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/components/${payload.componentCode}/${payload.path1}/${payload.path2}/${payload.path3}/${payload.path4}/${payload.path5}/${payload.path6}/${payload.path7}/${payload.path8}`,
    },
    [LowcodeComponentResourceController.getStaticResource9.method]: {
      summary: '获取资源：九级目录',
      method: 'get',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/components/${payload.componentCode}/${payload.path1}/${payload.path2}/${payload.path3}/${payload.path4}/${payload.path5}/${payload.path6}/${payload.path7}/${payload.path8}/${payload.path9}`,
    },
  },
}
