// This file is automatically generated

// 低开应用模板管理

import { LowcodeAppTemplateController } from '@controller'
export default {
  actions: {
    [LowcodeAppTemplateController.create.method]: {
      summary: '创建项目模板',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/lc-app-templates`,
    },
    [LowcodeAppTemplateController.createByFile.method]: {
      summary: '创建项目模板（根据上传文件创建）',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/lc-app-templates/actions/import-file`,
    },
    [LowcodeAppTemplateController.delete.method]: {
      summary: '删除项目模板：支持批量删除',
      method: 'delete',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/lc-app-templates`,
    },
    [LowcodeAppTemplateController.disabled.method]: {
      summary: '状态设置：禁用',
      method: 'put',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/lc-app-templates/${payload.id}/disabled`,
    },
    [LowcodeAppTemplateController.existenceByCode.method]: {
      summary: '校验code是否存在',
      method: 'get',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/lc-app-templates/exist`,
    },
    [LowcodeAppTemplateController.exportAppTemplate.method]: {
      summary: '导出应用模板',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/lc-app-templates/actions/export`,
    },
    [LowcodeAppTemplateController.get.method]: {
      summary: '根据id或者code查询应用模板信息',
      method: 'get',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/lc-app-templates/${payload.id}`,
    },
    [LowcodeAppTemplateController.importTemplate.method]: {
      summary: '选择应用模板导入到指定应用中',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/lc-app-templates/${payload.appCode}/import-templates`,
    },
    [LowcodeAppTemplateController.queryWithPage.method]: {
      summary: '分页查询应用模板列表',
      method: 'get',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/lc-app-templates`,
    },
    [LowcodeAppTemplateController.rename.method]: {
      summary: '修改项目模板：只支持修改名称和描述',
      method: 'put',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/lc-app-templates/${payload.id}/rename`,
    },
    [LowcodeAppTemplateController.startup.method]: {
      summary: '状态设置：启用',
      method: 'put',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/lc-app-templates/${payload.id}/startup`,
    },
  },
}
