// This file is automatically generated

// 素材库分组管理

import { MaterialGroupController } from '@controller'
export default {
  actions: {
    [MaterialGroupController.create.method]: {
      summary: '新增素材库分组',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/material-groups`,
    },
    [MaterialGroupController.delete.method]: {
      summary: '删除素材库分组',
      method: 'delete',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/material-groups`,
    },
    [MaterialGroupController.findMaterialGroupById.method]: {
      summary: '根据主键查询',
      method: 'get',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/material-groups/${payload.id}`,
    },
    [MaterialGroupController.isExistByCode.method]: {
      summary: '校验Code是否存在',
      method: 'get',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/material-groups/exist`,
    },
    [MaterialGroupController.queryMaterialGroupWithPage.method]: {
      summary: '分页条件查询',
      method: 'get',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/material-groups`,
    },
    [MaterialGroupController.update.method]: {
      summary: '修改素材库分组',
      method: 'put',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/material-groups`,
    },
  },
}
