// This file is automatically generated

// 菜单使用记录

import { MenuUsageRecordController } from '@controller'
export default {
  actions: {
    [MenuUsageRecordController.create.method]: {
      summary: '新增/修改菜单使用记录',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/menu-record/click/menu`,
    },
    [MenuUsageRecordController.queryCommonMenusByCurrentUser.method]: {
      summary: '查询经常当前登陆人常用菜单',
      method: 'get',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/menu-record/common-menu`,
    },
  },
}
