// This file is automatically generated

// 在线用户管理

import { OnlineUserController } from '@controller'
export default {
  actions: {
    [OnlineUserController.clear.method]: {
      summary: '清除数据库中缓存里没有的在线用户',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/online-users/clear`,
    },
    [OnlineUserController.create.method]: {
      summary: '新增在线用户',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/online-users`,
    },
    [OnlineUserController.delete.method]: {
      summary: '删除在线用户根据id',
      method: 'delete',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/online-users/${payload.id}`,
    },
    [OnlineUserController.deleteByUniqueId.method]: {
      summary: '删除在线用户根据uniqueId',
      method: 'delete',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/online-users`,
    },
    [OnlineUserController.findOnlineUser.method]: {
      summary: '根据id查在线用户',
      method: 'get',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/online-users/${payload.id}`,
    },
    [OnlineUserController.logout.method]: {
      summary: '强制下线',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/online-users/logout/${payload.uniqueId}`,
    },
    [OnlineUserController.queryOnlineUser.method]: {
      summary: '条件查询在线用户',
      method: 'get',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/online-users`,
    },
    [OnlineUserController.queryOnlineUserWithPage.method]: {
      summary: '分页查询在线用户',
      method: 'get',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/online-users/page`,
    },
    [OnlineUserController.update.method]: {
      summary: '修改在线用户',
      method: 'put',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/online-users`,
    },
  },
}
