// This file is automatically generated

// 操作日志管理

import { OperationLogController } from '@controller'
export default {
  actions: {
    [OperationLogController.exportOperationLogsForSys.method]: {
      summary: '根据条件导出日志平台级',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/operation-logs/export-logs/sys`,
    },
    [OperationLogController.exportOperationLogsForTenant.method]: {
      summary: '根据条件导出日志租户级',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/operation-logs/export-logs/tenant`,
    },
    [OperationLogController.findOperationLogDetail.method]: {
      summary: '根据ID查询日志详情',
      method: 'get',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/operation-logs/${payload.id}/`,
    },
    [OperationLogController.findTenantOperationLogDetail.method]: {
      summary: '根据ID查询租户日志详情',
      method: 'get',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/operation-logs/detail/${payload.id}`,
    },
    [OperationLogController.logsToHistory.method]: {
      summary: '日志转历史',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/operation-logs/to-history`,
    },
    [OperationLogController.queryOperationLogForSys.method]: {
      summary: '平台级根据条件查询操作日志',
      method: 'get',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/operation-logs/sys`,
    },
    [OperationLogController.queryOperationLogForTenant.method]: {
      summary: '租户级根据条件查询操作日志',
      method: 'get',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/operation-logs/tenant`,
    },
  },
}
