// This file is automatically generated

// 组织权限中心首页管理

import { OrgAuthorityCenterController } from '@controller'
export default {
  actions: {
    [OrgAuthorityCenterController.queryTenantStatistics.method]: {
      summary: '获取租户下的相关统计',
      method: 'get',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/org-authority-centers/tenant`,
    },
  },
}
