// This file is automatically generated

// 门户管理

import { PortalController } from '@controller'
export default {
  actions: {
    [PortalController.bindRoleWidgets.method]: {
      summary: 'portal绑定角色',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/portals/${payload.id}/roles`,
    },
    [PortalController.createWithPrivate.method]: {
      summary: '新建(用户)',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/portals/private`,
    },
    [PortalController.createWithPublic.method]: {
      summary: '新建(管理员)',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/portals/public`,
    },
    [PortalController.deleteWithPrivate.method]: {
      summary: '删除、批量删除(用户)',
      method: 'delete',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/portals/private`,
    },
    [PortalController.deleteWithPublic.method]: {
      summary: '删除、批量删除(管理员)',
      method: 'delete',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/portals/public`,
    },
    [PortalController.existenceByCode.method]: {
      summary: '校验code是否存在(公共接口)',
      method: 'get',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/portals/${payload.code}/exist`,
    },
    [PortalController.getByCodeWithPrivate.method]: {
      summary: '根据code or id查询(用户)',
      method: 'get',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/portals/private/${payload.code}`,
    },
    [PortalController.getByCodeWithPublic.method]: {
      summary: '根据code or id查询(管理员)',
      method: 'get',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/portals/public/${payload.code}`,
    },
    [PortalController.queryByCurrentUser.method]: {
      summary: '获取当前登录用户的portals(公共接口)',
      method: 'get',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/portals/current`,
    },
    [PortalController.queryRolesByPortalIdWithPage.method]: {
      summary: '分页查询portal绑定的角色列表',
      method: 'get',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/portals/${payload.id}/roles`,
    },
    [PortalController.queryWithPrivatePage.method]: {
      summary: '分页条件查询portals列表(用户)',
      method: 'get',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/portals/private`,
    },
    [PortalController.queryWithPublicPage.method]: {
      summary: '分页条件查询portals列表(管理员)',
      method: 'get',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/portals/public`,
    },
    [PortalController.unbindRolePortals.method]: {
      summary: 'portal解绑角色',
      method: 'delete',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/portals/${payload.id}/roles`,
    },
    [PortalController.updateContentWithPrivate.method]: {
      summary: '修改内容(用户)',
      method: 'put',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/portals/private/${payload.id}/content`,
    },
    [PortalController.updateContentWithPublic.method]: {
      summary: '修改内容(管理员)',
      method: 'put',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/portals/public/${payload.id}/content`,
    },
    [PortalController.updateWithPrivate.method]: {
      summary: '修改(用户)',
      method: 'put',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/portals/private/${payload.id}/basic`,
    },
    [PortalController.updateWithPublic.method]: {
      summary: '修改基本信息(管理员)',
      method: 'put',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/portals/public/${payload.id}/basic`,
    },
  },
}
