// This file is automatically generated

// 岗位管理

import { PositionController } from '@controller'
export default {
  actions: {
    [PositionController.create.method]: {
      summary: '新增岗位',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/positions`,
    },
    [PositionController.createRolesInPosition.method]: {
      summary: '岗位批量添加角色',
      method: 'put',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/positions/${payload.positionId}/roles`,
    },
    [PositionController.deleteByIds.method]: {
      summary: '根据主键集合批量删除岗位',
      method: 'delete',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/positions`,
    },
    [PositionController.deleteRolesInPosition.method]: {
      summary: '岗位批量移除角色',
      method: 'delete',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/positions/${payload.positionId}/roles`,
    },
    [PositionController.findPositionById.method]: {
      summary: '根据id查询岗位',
      method: 'get',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/positions/info/${payload.id}`,
    },
    [PositionController.findPositionIsExist.method]: {
      summary: '校验当前租户下是否存在岗位编码或岗位名称，true存在',
      method: 'get',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/positions/exist`,
    },
    [PositionController.queryPositionByIds.method]: {
      summary: '根据多个ID字符串查询岗位',
      method: 'get',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/positions/info/ids`,
    },
    [PositionController.queryPositionTypes.method]: {
      summary: '条件查询岗位类型,分页展示',
      method: 'get',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/positions/types`,
    },
    [PositionController.queryPositionsByCriteria.method]: {
      summary: '按条件查询岗位，分页展示',
      method: 'get',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/positions`,
    },
    [PositionController.queryRolesInPosition.method]: {
      summary: '查询岗位下的角色信息，分页展示',
      method: 'get',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/positions/${payload.positionId}/roles`,
    },
    [PositionController.update.method]: {
      summary: '修改岗位',
      method: 'put',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/positions`,
    },
  },
}
