// This file is automatically generated

// 导出管理

import { RdcloudExportExcelController } from '@controller'
export default {
  actions: {
    [RdcloudExportExcelController.exportExcel.method]: {
      summary: '部门统计数据导出excel',
      method: 'get',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/export/orgs-statistic`,
    },
  },
}
