// This file is automatically generated

// 用户统计分析管理

import { RdcloudConversationUserStatisticsController } from '@controller'
export default {
  actions: {
    [RdcloudConversationUserStatisticsController.queryUserStatistics.method]: {
      summary: '获取单个用户统计分析',
      method: 'get',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/user-statistics/${payload.userName}`,
    },
  },
}
