// This file is automatically generated

// GPT模板管理

import { RdcloudTemplateController } from '@controller'
export default {
  actions: {
    [RdcloudTemplateController.create.method]: {
      summary: '创建模板',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/templates`,
    },
    [RdcloudTemplateController.deleteByIds.method]: {
      summary: '按主键集合删除(参数放body)',
      method: 'put',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/templates/bulk-delete`,
    },
    [RdcloudTemplateController.generateContent.method]: {
      summary: '根据模板生成内容',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/templates/${payload.id}/generate-content`,
    },
    [RdcloudTemplateController.getRdcloudTemplate.method]: {
      summary: '查询指定模板',
      method: 'get',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/templates/${payload.idOrCode}`,
    },
    [RdcloudTemplateController.queryRdcloudTemplatesWithPage.method]: {
      summary: '查询模板列表',
      method: 'get',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/templates`,
    },
    [RdcloudTemplateController.update.method]: {
      summary: '更新模板',
      method: 'put',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/templates`,
    },
  },
}
