// This file is automatically generated

// 部门统计分析管理

import { RdcloudConversationOrgStatisticsController } from '@controller'
export default {
  actions: {
    [RdcloudConversationOrgStatisticsController.findOrgTree.method]: {
      summary: '获取组织机构树',
      method: 'get',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/org-statistics/tree`,
    },
    [RdcloudConversationOrgStatisticsController.getChildrenOrgs.method]: {
      summary: '获取子机构列表',
      method: 'get',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/org-statistics/${payload.orgId}/children`,
    },
    [RdcloudConversationOrgStatisticsController.getHeatMap.method]: {
      summary: '获取单个部门热力图(只有一级、二级部门[orgLever&#x3D;2/3]有此表)',
      method: 'get',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/org-statistics/${payload.orgId}/heat-map`,
    },
    [RdcloudConversationOrgStatisticsController.getSumStatistics.method]: {
      summary: '获取单个部门统计总数(只有一级、二级部门[orgLever&#x3D;2/3]有此表)',
      method: 'get',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/org-statistics/${payload.orgId}/data`,
    },
    [RdcloudConversationOrgStatisticsController.queryOrgStatistics.method]: {
      summary: '获取单个部门统计分析(只有一级、二级部门[orgLever&#x3D;2/3]有此表)',
      method: 'get',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/org-statistics/${payload.orgId}`,
    },
    [RdcloudConversationOrgStatisticsController.queryOrgStatistics4GptModel.method]: {
      summary: '获取部门下的GPT模型饼图分析(只有一级、二级部门[orgLever&#x3D;2/3]下有此表)',
      method: 'get',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/org-statistics/${payload.orgId}/gpt-model`,
    },
    [RdcloudConversationOrgStatisticsController.queryOrgStatisticsByOrg.method]: {
      summary: '获取父部门下子部门的排名分析(只有一级部门[orgLever&#x3D;2]下有此表)',
      method: 'get',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/org-statistics/${payload.parentOrgId}/orgs`,
    },
    [RdcloudConversationOrgStatisticsController.queryUserStatisticsByOrg.method]: {
      summary: '获取部门下所有用户排名分析(只有一级、二级部门[orgLever&#x3D;2/3]下有此表)',
      method: 'get',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/org-statistics/${payload.orgId}/users`,
    },
  },
}
