// This file is automatically generated

// 个人画像管理

import { RdcloudPersonalizationController } from '@controller'
export default {
  actions: {
    [RdcloudPersonalizationController.getRdcloudPersonalization.method]: {
      summary: '获取个人画像',
      method: 'get',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/personalization/${payload.userName}`,
    },
  },
}
