// This file is automatically generated

// 资源分组代理管理

import { ResGroupProxyController } from '@controller'
export default {
  actions: {
    [ResGroupProxyController.create.method]: {
      summary: '创建资源分组信息',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/afc-proxy/res-groups/create`,
    },
    [ResGroupProxyController.findResGroup.method]: {
      summary: '根据id查找资源分组信息',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/afc-proxy/res-groups/find-res-group`,
    },
    [ResGroupProxyController.findResGroupByCodeAndTenantId.method]: {
      summary: '根据分组编码与租户编号查找资源分组信息',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/afc-proxy/res-groups/find-res-group-by-code-and-tenant-id`,
    },
    [ResGroupProxyController.queryResGroupsByAppId.method]: {
      summary: '根据应用编号查找资源分组信息',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/afc-proxy/res-groups/query-res-groups-by-app-id`,
    },
    [ResGroupProxyController.queryResGroupsByCriteria.method]: {
      summary: '分页查找资源分组信息',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/afc-proxy/res-groups/query-res-groups-by-criteria`,
    },
    [ResGroupProxyController.queryResGroupsByTenantId.method]: {
      summary: '根据租户编号查找资源分组信息',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/afc-proxy/res-groups/query-res-groups-by-tenant-id`,
    },
  },
}
