// This file is automatically generated

// 资源分组管理

import { ResGroupController } from '@controller'
export default {
  actions: {
    [ResGroupController.create.method]: {
      summary: '新增资源分组',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/res-groups`,
    },
    [ResGroupController.deleteByIds.method]: {
      summary: '按主键集合删除(参数放body)',
      method: 'put',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/res-groups/bulk-delete`,
    },
    [ResGroupController.findResGroup.method]: {
      summary: '根据id查询',
      method: 'get',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/res-groups/${payload.id}`,
    },
    [ResGroupController.isExist.method]: {
      summary: '校验code是否重复',
      method: 'get',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/res-groups/exist/${payload.code}/${payload.tenantId}`,
    },
    [ResGroupController.queryResGroupsByCriteria.method]: {
      summary: '分页查询资源分组列表',
      method: 'get',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/res-groups`,
    },
    [ResGroupController.update.method]: {
      summary: '修改资源分组-基础信息',
      method: 'put',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/res-groups`,
    },
  },
}
