// This file is automatically generated

// 资源管理

import { ResourceController } from '@controller'
export default {
  actions: {
    [ResourceController.create.method]: {
      summary: '新增资源',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/resources`,
    },
    [ResourceController.deleteByIds.method]: {
      summary: '按主键集合删除(参数放body)',
      method: 'put',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/resources/bulk-delete`,
    },
    [ResourceController.findResource.method]: {
      summary: '根据id查询',
      method: 'get',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/resources/${payload.id}`,
    },
    [ResourceController.isExist.method]: {
      summary: '校验code是否重复',
      method: 'get',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/resources/exist/${payload.code}/${payload.tenantId}`,
    },
    [ResourceController.queryFunctionCodesByCurrentUser.method]: {
      summary: '查询当前登录用户功能码',
      method: 'get',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/resources/current/function`,
    },
    [ResourceController.queryFunctionCodesByCurrentUserWithAppId.method]: {
      summary: '查询当前登录用户应用功能码(应用功能码)',
      method: 'get',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/resources/current/app-functions/${payload.appId}`,
    },
    [ResourceController.queryResourcesByCriteria.method]: {
      summary: '分页查询资源列表',
      method: 'get',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/resources`,
    },
    [ResourceController.queryUrlResources.method]: {
      summary: '查找url资源列表',
      method: 'get',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/resources/url-resources`,
    },
    [ResourceController.update.method]: {
      summary: '修改资源-基础信息',
      method: 'put',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/resources`,
    },
    [ResourceController.updateBiResourceContent.method]: {
      summary: '同步修改BI资源ID',
      method: 'put',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/resources/sync/bi-resource`,
    },
    [ResourceController.updateTypes.method]: {
      summary: '批量修改资源分类',
      method: 'put',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/resources/types-change/${payload.resGroupId}`,
    },
  },
}
