// This file is automatically generated

// 角色管理

import { RoleController } from '@controller'
export default {
  actions: {
    [RoleController.create.method]: {
      summary: '新增角色',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/roles`,
    },
    [RoleController.deleteByIds.method]: {
      summary: '按主键集合删除(参数放body),单个删除和批量删除复用一个接口',
      method: 'delete',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/roles`,
    },
    [RoleController.existenceByCode.method]: {
      summary: '校验code是否存在',
      method: 'get',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/roles/exist`,
    },
    [RoleController.findRoleById.method]: {
      summary: '根据主键查询',
      method: 'get',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/roles/${payload.id}`,
    },
    [RoleController.queryAppRolesWithPage.method]: {
      summary: '分页查询role列表(应用管理)',
      method: 'get',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/roles/app-roles/${payload.appId}`,
    },
    [RoleController.queryRoleByIds.method]: {
      summary: '选人组件根据数组查询角色',
      method: 'get',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/roles/info`,
    },
    [RoleController.queryRolesWithPage.method]: {
      summary: '分页查询role列表',
      method: 'get',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/roles`,
    },
    [RoleController.update.method]: {
      summary: '修改角色-基础信息',
      method: 'put',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/roles`,
    },
  },
}
