// This file is automatically generated

// 安全策略

import { SafetyController } from '@controller'
export default {
  actions: {
    [SafetyController.create.method]: {
      summary: '新增密码策略',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/safeties`,
    },
    [SafetyController.getSafetySite.method]: {
      summary: '查询密码策略',
      method: 'get',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/safeties/${payload.tenantId}`,
    },
    [SafetyController.update.method]: {
      summary: '修改密码策略',
      method: 'put',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/safeties`,
    },
  },
}
