// This file is automatically generated

// 白名单

import { SafetyWhitelistController } from '@controller'
export default {
  actions: {
    [SafetyWhitelistController.create.method]: {
      summary: '添加白名单员工',
      method: 'put',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/safety-whitelist`,
    },
    [SafetyWhitelistController.createWaterMarkSafetyWhite.method]: {
      summary: '添加水印白名单员工',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/safety-whitelist/water-mark`,
    },
    [SafetyWhitelistController.deleteByEmployeeIds.method]: {
      summary: '删除水印白名单员工',
      method: 'delete',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/safety-whitelist/water-mark`,
    },
    [SafetyWhitelistController.deleteByIds.method]: {
      summary: '删除白名单员工',
      method: 'delete',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/safety-whitelist`,
    },
    [SafetyWhitelistController.deleteSafetyByEmployeeIds.method]: {
      summary: '删除密码策略白名单人员',
      method: 'delete',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/safety-whitelist/safety`,
    },
    [SafetyWhitelistController.querySafetyWhitelist.method]: {
      summary: '查询租户下白名单',
      method: 'get',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/safety-whitelist`,
    },
  },
}
