// This file is automatically generated

// 选人组件管理

import { SelectionComponentController } from '@controller'
export default {
  actions: {
    [SelectionComponentController.queryChildByParentId.method]: {
      summary: '根据机构id查出子机构',
      method: 'get',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/selection-components/child`,
    },
    [SelectionComponentController.queryEmployee.method]: {
      summary: '条件查询员工',
      method: 'get',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/selection-components/employees/tree`,
    },
    [SelectionComponentController.queryEmployeeByOrg.method]: {
      summary: '根据机构id查询出当前机构下所有员工',
      method: 'get',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/selection-components/employees`,
    },
    [SelectionComponentController.queryEmployeeForDepartment.method]: {
      summary: '部门根据条件查询员工，根据登录用户判断是租户管理员或者机构管理员',
      method: 'get',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/selection-components/dep/employee`,
    },
    [SelectionComponentController.queryEmployeeForOrg.method]: {
      summary: '机构根据条件查询员工，根据登录用户判断是租户管理员或者机构管理员',
      method: 'get',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/selection-components/org/employee`,
    },
    [SelectionComponentController.queryEmployeeInOrg.method]: {
      summary: '查询同部门下的员工',
      method: 'get',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/selection-components/${payload.orgId}/employees`,
    },
    [SelectionComponentController.queryEmployees.method]: {
      summary: '员工多选，根据根节点机构id',
      method: 'get',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/selection-components/bulk-selection`,
    },
    [SelectionComponentController.queryOrg.method]: {
      summary: '查询一级机构，根据登录用户判断租户管理员或者机构管理员',
      method: 'get',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/selection-components/org`,
    },
    [SelectionComponentController.queryOrgFullPath.method]: {
      summary: '查询机构的全路径',
      method: 'get',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/selection-components/org/full-path`,
    },
    [SelectionComponentController.queryUser.method]: {
      summary: '条件查询账号',
      method: 'get',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/selection-components/users/tree`,
    },
  },
}
