// This file is automatically generated

// 素材库管理

import { SourceMaterialController } from '@controller'
export default {
  actions: {
    [SourceMaterialController.create.method]: {
      summary: '新增素材',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/materials`,
    },
    [SourceMaterialController.delete.method]: {
      summary: '删除素材',
      method: 'delete',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/materials`,
    },
    [SourceMaterialController.deleteBtCode.method]: {
      summary: '根据Code删除素材',
      method: 'delete',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/materials/bulk-code`,
    },
    [SourceMaterialController.downloadFontIcon.method]: {
      summary: '下载字体图标',
      method: 'get',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/materials/actions/download/${payload.materialGroupId}`,
    },
    [SourceMaterialController.downloadSvgFontIcon.method]: {
      summary: '根据Code展示图标',
      method: 'get',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/materials/font/actions/show`,
    },
    [SourceMaterialController.exportMaterials.method]: {
      summary: '素材库资源导出',
      method: 'get',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/materials/actions/export`,
    },
    [SourceMaterialController.findSourceMaterialByCode.method]: {
      summary: '根据Code查询',
      method: 'get',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/materials`,
    },
    [SourceMaterialController.findSourceMaterialById.method]: {
      summary: '根据主键查询',
      method: 'get',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/materials/${payload.id}`,
    },
    [SourceMaterialController.getCssFile.method]: {
      summary: '获取css文件',
      method: 'get',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/materials/font/${payload.groupCode}/iconfont.css`,
    },
    [SourceMaterialController.getEotFile.method]: {
      summary: '获取eot文件',
      method: 'get',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/materials/font/${payload.groupCode}/iconfont.eot`,
    },
    [SourceMaterialController.getMd5.method]: {
      summary: '获取素材CODE',
      method: 'get',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/materials/md5`,
    },
    [SourceMaterialController.getSvgFile.method]: {
      summary: '获取svg文件',
      method: 'get',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/materials/font/${payload.groupCode}/iconfont.svg`,
    },
    [SourceMaterialController.getTtfFile.method]: {
      summary: '获取ttf文件',
      method: 'get',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/materials/font/${payload.groupCode}/iconfont.ttf`,
    },
    [SourceMaterialController.getWoff2File.method]: {
      summary: '获取woff2文件',
      method: 'get',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/materials/font/${payload.groupCode}/iconfont.woff2`,
    },
    [SourceMaterialController.getWoffFile.method]: {
      summary: '获取woff文件',
      method: 'get',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/materials/font/${payload.groupCode}/iconfont.woff`,
    },
    [SourceMaterialController.importMaterials.method]: {
      summary: '素材库资源导入',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/materials/actions/import/${payload.importSetting}`,
    },
    [SourceMaterialController.isExistByCode.method]: {
      summary: '校验Code是否存在',
      method: 'get',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/materials/exist`,
    },
    [SourceMaterialController.isExistByName.method]: {
      summary: '根据名称校验是否存在',
      method: 'get',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/materials/exist/name`,
    },
    [SourceMaterialController.querySourceMaterialByCriteria.method]: {
      summary: '条件查询',
      method: 'get',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/materials/list`,
    },
    [SourceMaterialController.querySourceMaterialWithPage.method]: {
      summary: '分页条件查询',
      method: 'get',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/materials/page`,
    },
    [SourceMaterialController.update.method]: {
      summary: '修改素材',
      method: 'put',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/materials`,
    },
    [SourceMaterialController.updateByCode.method]: {
      summary: '根据Code修改素材',
      method: 'put',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/materials/update/${payload.code}`,
    },
    [SourceMaterialController.uploadMaterial.method]: {
      summary: '素材上传',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/materials/actions/upload`,
    },
  },
}
