// This file is automatically generated

// 站内信管理

import { StationMessageController } from '@controller'
export default {
  actions: {
    [StationMessageController.create.method]: {
      summary: '创建站内信',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/station`,
    },
    [StationMessageController.deleteBatch.method]: {
      summary: '批量删除站内信',
      method: 'delete',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/station`,
    },
    [StationMessageController.haveRead.method]: {
      summary: '修改待阅状态为已阅',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/station/have-read`,
    },
    [StationMessageController.queryPersonalStationMessagesByCriteria.method]: {
      summary: '条件查询人员站内信列表',
      method: 'get',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/station/criteria`,
    },
    [StationMessageController.queryPersonalUnreadStationMessages.method]: {
      summary: '查询当前用户未读消息数量',
      method: 'get',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/station/unread`,
    },
    [StationMessageController.queryStationMessageDetailById.method]: {
      summary: '查询单个站内信详情',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/station/detail/${payload.id}`,
    },
  },
}
