// This file is automatically generated

// 讯飞集成-组织机构管理

import { SyncOrgUserController } from '@controller'
export default {
  actions: {
    [SyncOrgUserController.syncOrgEmpUser.method]: {
      summary: '同步组织结构、员工、用户',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/integration/orgs/sync/org-users/${payload.strategy}`,
    },
  },
}
