// This file is automatically generated

// 系统变量

import { SysVariableController } from '@controller'
export default {
  actions: {
    [SysVariableController.create.method]: {
      summary: '新增系统变量',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/system-variables`,
    },
    [SysVariableController.deleteByIds.method]: {
      summary: '按主键集合删除(参数放body)',
      method: 'put',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/system-variables/bulk-delete`,
    },
    [SysVariableController.findSystemVariable.method]: {
      summary: '根据id查询',
      method: 'get',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/system-variables/${payload.id}`,
    },
    [SysVariableController.getDevopsDefaultApp.method]: {
      summary: '查询默认的app占用内存大小',
      method: 'get',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/system-variables/default-app-memory`,
    },
    [SysVariableController.isExist.method]: {
      summary: '校验code是否重复',
      method: 'get',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/system-variables/exist/${payload.code}/${payload.tenantId}`,
    },
    [SysVariableController.isNameExist.method]: {
      summary: '校验name是否重复',
      method: 'get',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/system-variables/exist/name/${payload.name}/${payload.tenantId}`,
    },
    [SysVariableController.querySystemVariablesByCriteria.method]: {
      summary: '分页查询系统变量列表',
      method: 'get',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/system-variables`,
    },
    [SysVariableController.replaceWithSystemVariables.method]: {
      summary: '转换系统变量',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/system-variables/resolveSysVariable`,
    },
    [SysVariableController.update.method]: {
      summary: '修改系统变量-基础信息',
      method: 'put',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/system-variables`,
    },
  },
}
