// This file is automatically generated

// 租户升级管理

import { TenantUpgradeController } from '@controller'
export default {
  actions: {
    [TenantUpgradeController.queryTenantUpgradeTemplateData.method]: {
      summary: '查看更新部分模板数据',
      method: 'get',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/upgrades`,
    },
    [TenantUpgradeController.updateTenantTemplateData.method]: {
      summary: '升级资源更新模板数据',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/upgrades`,
    },
  },
}
