// This file is automatically generated

// testa-controller

import { TestaController } from '@controller'
export default {
  actions: {
    [TestaController.test1.method]: {
      summary: 'test1',
      method: 'get',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/test/`,
    },
  },
}
