// This file is automatically generated

// test

import { testController } from '@controller'
export default {
  actions: {
    [testController.findRoleById.method]: {
      summary: 'findRoleById',
      method: 'get',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/duan/test`,
    },
  },
}
