// This file is automatically generated

// 水印管理

import { WaterMarkController } from '@controller'
export default {
  actions: {
    [WaterMarkController.create.method]: {
      summary: '创建水印',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/water_marks`,
    },
    [WaterMarkController.findWaterMark.method]: {
      summary: '根据id查询',
      method: 'get',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/water_marks`,
    },
    [WaterMarkController.update.method]: {
      summary: '修改水印',
      method: 'put',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/water_marks`,
    },
  },
}
