// This file is automatically generated

// 工作通知管理

import { WorkNoticeController } from '@controller'
export default {
  actions: {
    [WorkNoticeController.create.method]: {
      summary: '新增',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/work-notice`,
    },
    [WorkNoticeController.delete.method]: {
      summary: '删除(支持批量删除)',
      method: 'delete',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/work-notice`,
    },
    [WorkNoticeController.getById.method]: {
      summary: '根据id查询',
      method: 'get',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/work-notice/${payload.id}`,
    },
    [WorkNoticeController.queryWithPage.method]: {
      summary: '分页条件查询列表',
      method: 'get',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/work-notice`,
    },
    [WorkNoticeController.update.method]: {
      summary: '修改',
      method: 'put',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/work-notice`,
    },
  },
}
