// This file is automatically generated

// 讯飞集成-登录管理

import { XFLoginController } from '@controller'
export default {
  actions: {
    [XFLoginController.login.method]: {
      summary: '登录，不做安全策略校验',
      method: 'post',
      apiPrefix: '/afc',
      url: (payload) => `/api/afc/integration/login`,
    },
  },
}
