// This file is automatically generated

// BFP流程任务中心管理

import { LowcodeBfpTaskCenterController } from '@controller'
export default {
  actions: {
    [LowcodeBfpTaskCenterController.queryPersonFinishWorklistWithPage.method]: {
      summary: '分页查询已办工作列表',
      method: 'get',
      apiPrefix: true,
      url: (payload) => `/api/lowcode/taskcenter/worklist/person-finish`,
    },
    [LowcodeBfpTaskCenterController.queryPersonWorklistWithPage.method]: {
      summary: '分页查询待办工作列表',
      method: 'get',
      apiPrefix: true,
      url: (payload) => `/api/lowcode/taskcenter/worklist/person`,
    },
  },
}
