// This file is automatically generated

// 低开运行时管理

import { LowcodeRuntimeController } from '@controller'
export default {
  actions: {
    [LowcodeRuntimeController.queryBizLogics.method]: {
      summary: '查询运行时逻辑流',
      method: 'get',
      apiPrefix: true,
      url: (payload) => `/api/lowcode/runtimes/biz-logics`,
    },
    [LowcodeRuntimeController.queryBizlets.method]: {
      summary: '查询运行时运算逻辑',
      method: 'get',
      apiPrefix: true,
      url: (payload) => `/api/lowcode/runtimes/bizlets`,
    },
    [LowcodeRuntimeController.queryEosservices.method]: {
      summary: '查询运行时EOS服务',
      method: 'get',
      apiPrefix: true,
      url: (payload) => `/api/lowcode/runtimes/eosservices`,
    },
    [LowcodeRuntimeController.querySdoTypes.method]: {
      summary: '查询运行时sdo类型',
      method: 'get',
      apiPrefix: true,
      url: (payload) => `/api/lowcode/runtimes/sdo-types`,
    },
  },
}
