// This file is automatically generated

// 低开资源回收站管理

import { LowcodeResourceRecycleController } from '@controller'
export default {
  actions: {
    [LowcodeResourceRecycleController.queryWithPage.method]: {
      summary: '分页查询低开资源资源回收站资源列表',
      method: 'get',
      apiPrefix: true,
      url: (payload) => `/api/lowcode/res-recycles`,
    },
    [LowcodeResourceRecycleController.restore.method]: {
      summary: '还原回收站内自定资源(支持批量还原)',
      method: 'put',
      apiPrefix: true,
      url: (payload) => `/api/lowcode/res-recycles/actions/restore`,
    },
  },
}
