// This file is automatically generated

// 低开资源关联关系管理

import { LowcodeResourceIndexController } from '@controller'
export default {
  actions: {
    [LowcodeResourceIndexController.queryRelationModels.method]: {
      summary: '根据实体名称查询引用的实体或者被引用的实体信息',
      method: 'get',
      apiPrefix: true,
      url: (payload) => `/api/lowcode/res-relations/sdo-models`,
    },
    [LowcodeResourceIndexController.queryRelationResources.method]: {
      summary: '查询实体关联的资源信息',
      method: 'get',
      apiPrefix: true,
      url: (payload) => `/api/lowcode/res-relations/source-resources`,
    },
  },
}
