// This file is automatically generated

// 低开应用模板管理

import { LowcodeProjectTemplateController } from '@controller'
export default {
  actions: {
    [LowcodeProjectTemplateController.create.method]: {
      summary: '创建项目模板',
      method: 'post',
      apiPrefix: true,
      url: (payload) => `/api/lowcode/project-templates`,
    },
    [LowcodeProjectTemplateController.delete.method]: {
      summary: '删除项目模板：支持批量删除',
      method: 'delete',
      apiPrefix: true,
      url: (payload) => `/api/lowcode/project-templates`,
    },
    [LowcodeProjectTemplateController.disabled.method]: {
      summary: '状态设置：禁用',
      method: 'put',
      apiPrefix: true,
      url: (payload) => `/api/lowcode/project-templates/${payload.id}/disabled`,
    },
    [LowcodeProjectTemplateController.rename.method]: {
      summary: '修改项目模板：只支持修改名称和描述',
      method: 'put',
      apiPrefix: true,
      url: (payload) => `/api/lowcode/project-templates/${payload.id}/rename`,
    },
    [LowcodeProjectTemplateController.startup.method]: {
      summary: '状态设置：启用',
      method: 'put',
      apiPrefix: true,
      url: (payload) => `/api/lowcode/project-templates/${payload.id}/startup`,
    },
  },
}
