// This file is automatically generated

// 组件库管理

import { LowcodeComponentController } from '@controller'
export default {
  actions: {
    [LowcodeComponentController.create.method]: {
      summary: '创建组件',
      method: 'post',
      apiPrefix: true,
      url: (payload) => `/api/lowcode/components`,
    },
    [LowcodeComponentController.deletes.method]: {
      summary: '按主键删除组件分组(支持批量删除)',
      method: 'delete',
      apiPrefix: true,
      url: (payload) => `/api/lowcode/components`,
    },
    [LowcodeComponentController.existenceByCode.method]: {
      summary: '校验code是否存在',
      method: 'get',
      apiPrefix: true,
      url: (payload) => `/api/lowcode/components/${payload.code}/exist`,
    },
    [LowcodeComponentController.get.method]: {
      summary: '按id或者code查询组件库信息',
      method: 'get',
      apiPrefix: true,
      url: (payload) => `/api/lowcode/components/${payload.id}`,
    },
    [LowcodeComponentController.queryWithPage.method]: {
      summary: '分页查询组件库列表',
      method: 'get',
      apiPrefix: true,
      url: (payload) => `/api/lowcode/components`,
    },
    [LowcodeComponentController.update.method]: {
      summary: '修改',
      method: 'put',
      apiPrefix: true,
      url: (payload) => `/api/lowcode/components`,
    },
  },
}
