// This file is automatically generated

// 项目数据源管理

import { LowcodeDataSourceController } from '@controller'
export default {
  actions: {
    [LowcodeDataSourceController.createDBTables.method]: {
      summary: '创建数据库表(返回值key：successful,unsuccessful,error)',
      method: 'post',
      apiPrefix: true,
      url: (payload) => `/api/lowcode/datasources/actions/creation-db-tables`,
    },
    [LowcodeDataSourceController.dropTable.method]: {
      summary: '删除指定表',
      method: 'post',
      apiPrefix: true,
      url: (payload) => `/api/lowcode/datasources/actions/drop-table`,
    },
    [LowcodeDataSourceController.executeStructuredQL.method]: {
      summary: '执行SQL语句',
      method: 'post',
      apiPrefix: true,
      url: (payload) => `/api/lowcode/datasources/actions/es`,
    },
    [LowcodeDataSourceController.executeStructuredQLs.method]: {
      summary: '执行SQL脚本',
      method: 'post',
      apiPrefix: true,
      url: (payload) => `/api/lowcode/datasources/actions/ess`,
    },
    [LowcodeDataSourceController.generateColumnPropertyByRunSql.method]: {
      summary: '通过执行SQL查询，获取反射字段列表',
      method: 'post',
      apiPrefix: true,
      url: (payload) => `/api/lowcode/datasources/actions/generate-columns`,
    },
    [LowcodeDataSourceController.generateDataDL.method]: {
      summary: '生成DDL',
      method: 'post',
      apiPrefix: true,
      url: (payload) => `/api/lowcode/datasources/actions/creation-DataDL`,
    },
    [LowcodeDataSourceController.generateTableDL.method]: {
      summary: '生成表DDL',
      method: 'post',
      apiPrefix: true,
      url: (payload) => `/api/lowcode/datasources/actions/creation-TableDL`,
    },
    [LowcodeDataSourceController.getDatasourceByEntityName.method]: {
      summary: '查询指定实体所属数据源',
      method: 'get',
      apiPrefix: true,
      url: (payload) => `/api/lowcode/datasources/${payload.entityName}`,
    },
    [LowcodeDataSourceController.previewTableData.method]: {
      summary: '预览数据库表中数据',
      method: 'get',
      apiPrefix: true,
      url: (payload) => `/api/lowcode/datasources/${payload.dsName}/${payload.tableName}/preview/data`,
    },
    [LowcodeDataSourceController.queryAppDataSources.method]: {
      summary: '查询指定项目数据源信息',
      method: 'get',
      apiPrefix: true,
      url: (payload) => `/api/lowcode/datasources/apps/${payload.appCode}`,
    },
    [LowcodeDataSourceController.queryColumnsByTable.method]: {
      summary: '查询指定数据表列信息',
      method: 'get',
      apiPrefix: true,
      url: (payload) => `/api/lowcode/datasources/${payload.dsName}/${payload.tableName}/columns`,
    },
    [LowcodeDataSourceController.queryDataSources.method]: {
      summary: '查询项目数据源信息',
      method: 'get',
      apiPrefix: true,
      url: (payload) => `/api/lowcode/datasources`,
    },
    [LowcodeDataSourceController.queryTablesByDB.method]: {
      summary: '根据数据源查询默认数据表列表',
      method: 'get',
      apiPrefix: true,
      url: (payload) => `/api/lowcode/datasources/${payload.dsName}/tables`,
    },
    [LowcodeDataSourceController.saveTableData.method]: {
      summary: '编辑数据库表',
      method: 'post',
      apiPrefix: true,
      url: (payload) => `/api/lowcode/datasources/actions/save-table-data`,
    },
  },
}
