// This file is automatically generated

// 组件分组管理

import { LowcodeComponentGroupController } from '@controller'
export default {
  actions: {
    [LowcodeComponentGroupController.create.method]: {
      summary: '创建组件分组',
      method: 'post',
      apiPrefix: true,
      url: (payload) => `/api/lowcode/component-groups`,
    },
    [LowcodeComponentGroupController.deletes.method]: {
      summary: '按主键删除组件分组(支持批量删除)',
      method: 'delete',
      apiPrefix: true,
      url: (payload) => `/api/lowcode/component-groups`,
    },
    [LowcodeComponentGroupController.existenceByCode.method]: {
      summary: '校验code是否存在',
      method: 'get',
      apiPrefix: true,
      url: (payload) => `/api/lowcode/component-groups/${payload.code}/exist`,
    },
    [LowcodeComponentGroupController.findById.method]: {
      summary: '查询(支持id或者code)',
      method: 'get',
      apiPrefix: true,
      url: (payload) => `/api/lowcode/component-groups/${payload.id}`,
    },
    [LowcodeComponentGroupController.queryWithPage.method]: {
      summary: '分页查询',
      method: 'get',
      apiPrefix: true,
      url: (payload) => `/api/lowcode/component-groups`,
    },
    [LowcodeComponentGroupController.update.method]: {
      summary: '修改组件分组',
      method: 'put',
      apiPrefix: true,
      url: (payload) => `/api/lowcode/component-groups`,
    },
  },
}
