// This file is automatically generated

// 低开工具服务

import { LowcodeToolController } from '@controller'
export default {
  actions: {
    [LowcodeToolController.xmlOrJson.method]: {
      summary: 'xml-json互转',
      method: 'post',
      apiPrefix: true,
      url: (payload) => `/api/lowcode/tools/xml-or-json`,
    },
  },
}
