// This file is automatically generated

// 低开项目基线管理

import { LowcodeProjectBaselineController } from '@controller'
export default {
  actions: {
    [LowcodeProjectBaselineController.checkImportProjectBaseline.method]: {
      summary: '校验导入基线是否相同',
      method: 'get',
      apiPrefix: true,
      url: (payload) => `/api/lowcode/project-baselines/${payload.appName}/import-validation`,
    },
    [LowcodeProjectBaselineController.create.method]: {
      summary: '创建低开项目基线',
      method: 'post',
      apiPrefix: true,
      url: (payload) => `/api/lowcode/project-baselines`,
    },
    [LowcodeProjectBaselineController.delete.method]: {
      summary: '根据id删除低开项目基线信息(支持批量删除)',
      method: 'delete',
      apiPrefix: true,
      url: (payload) => `/api/lowcode/project-baselines`,
    },
    [LowcodeProjectBaselineController.deleteByAppName.method]: {
      summary: '根据低开应用名称删除低开项目基线信息',
      method: 'delete',
      apiPrefix: true,
      url: (payload) => `/api/lowcode/project-baselines/${payload.appName}`,
    },
    [LowcodeProjectBaselineController.existsByName.method]: {
      summary: '校验基线名称是否重复',
      method: 'get',
      apiPrefix: true,
      url: (payload) => `/api/lowcode/project-baselines/exist`,
    },
    [LowcodeProjectBaselineController.get.method]: {
      summary: '根据id查询项目基线',
      method: 'get',
      apiPrefix: true,
      url: (payload) => `/api/lowcode/project-baselines/${payload.id}`,
    },
    [LowcodeProjectBaselineController.getAppCurrentBaseline.method]: {
      summary: '查询应用当前基线信息',
      method: 'get',
      apiPrefix: true,
      url: (payload) => `/api/lowcode/project-baselines/${payload.appName}/current-baseline`,
    },
    [LowcodeProjectBaselineController.queryWithPage.method]: {
      summary: '分页查询低开项目基线列表',
      method: 'get',
      apiPrefix: true,
      url: (payload) => `/api/lowcode/project-baselines`,
    },
    [LowcodeProjectBaselineController.update.method]: {
      summary: '修改低开项目基线',
      method: 'put',
      apiPrefix: true,
      url: (payload) => `/api/lowcode/project-baselines`,
    },
  },
}
