// This file is automatically generated

// 低开三方服务集成管理

import { LowcodeServiceIntegrationController } from '@controller'
export default {
  actions: {
    [LowcodeServiceIntegrationController.createOperationSet.method]: {
      summary: '创建服务集',
      method: 'post',
      apiPrefix: true,
      url: (payload) => `/api/lowcode/si/operation-sets`,
    },
    [LowcodeServiceIntegrationController.deleteOperationSetById.method]: {
      summary: '删除服务集',
      method: 'delete',
      apiPrefix: true,
      url: (payload) => `/api/lowcode/si/operation-sets/${payload.id}`,
    },
    [LowcodeServiceIntegrationController.existsByCode.method]: {
      summary: '校验code是否重复',
      method: 'get',
      apiPrefix: true,
      url: (payload) => `/api/lowcode/si/exist`,
    },
    [LowcodeServiceIntegrationController.findOperationById.method]: {
      summary: '根据id查询服务操作(以及详情)',
      method: 'get',
      apiPrefix: true,
      url: (payload) => `/api/lowcode/si/operations/${payload.id}`,
    },
    [LowcodeServiceIntegrationController.findOperationEntitySetById.method]: {
      summary: '根据id查询服务操作实体集',
      method: 'get',
      apiPrefix: true,
      url: (payload) => `/api/lowcode/si/operation-entity-sets/${payload.id}`,
    },
    [LowcodeServiceIntegrationController.findOperationSetById.method]: {
      summary: '根据id查询服务集(查询详情)',
      method: 'get',
      apiPrefix: true,
      url: (payload) => `/api/lowcode/si/operation-sets/${payload.id}`,
    },
    [LowcodeServiceIntegrationController.importSwaggerToOperationSet.method]: {
      summary: '根据上传文件(优先)或者指定URL以及指定的swaggerApiIds来创建服务集',
      method: 'post',
      apiPrefix: true,
      url: (payload) => `/api/lowcode/si/swagger-import/import-to-operation-set`,
    },
    [LowcodeServiceIntegrationController.parseSwaggerApis.method]: {
      summary: '根据上传文件(优先)或者指定URL解析Swagger',
      method: 'post',
      apiPrefix: true,
      url: (payload) => `/api/lowcode/si/swagger-import/parse-apis`,
    },
    [LowcodeServiceIntegrationController.queryEntityDetails.method]: {
      summary: '查询指定三方服务实体信息',
      method: 'get',
      apiPrefix: true,
      url: (payload) => `/api/lowcode/si/operation-entity-sets/${payload.operationEntityId}/${payload.displayName}/entity/details`,
    },
    [LowcodeServiceIntegrationController.showForce.method]: {
      summary: '导入单个服务集校验：存在相同服务集是否强制导入',
      method: 'post',
      apiPrefix: true,
      url: (payload) => `/api/lowcode/si/actions/force/show`,
    },
    [LowcodeServiceIntegrationController.updateOperationSetBasicInfo.method]: {
      summary: '修改服务集(基本信息、认证配置、地址等)',
      method: 'put',
      apiPrefix: true,
      url: (payload) => `/api/lowcode/si/operation-sets/${payload.id}/basic`,
    },
  },
}
