// This file is automatically generated

// 低开资源管理

import { LowcodeResourceController } from '@controller'
export default {
  actions: {
    [LowcodeResourceController.clone.method]: {
      summary: '克隆低开资源',
      method: 'post',
      apiPrefix: true,
      url: (payload) => `/api/lowcode/resources/${payload.id}/clone`,
    },
    [LowcodeResourceController.compile.method]: {
      summary: '编译低开资源',
      method: 'post',
      apiPrefix: true,
      url: (payload) => `/api/lowcode/resources/${payload.id}/actions/compile`,
    },
    [LowcodeResourceController.create.method]: {
      summary: '创建低开资源',
      method: 'post',
      apiPrefix: true,
      url: (payload) => `/api/lowcode/resources`,
    },
    [LowcodeResourceController.delete.method]: {
      summary: '删除低开资源',
      method: 'delete',
      apiPrefix: true,
      url: (payload) => `/api/lowcode/resources/${payload.id}`,
    },
    [LowcodeResourceController.downloadExportTemplate.method]: {
      summary: '下载视图导入模板',
      method: 'post',
      apiPrefix: true,
      url: (payload) => `/api/lowcode/resources/download/export/template`,
    },
    [LowcodeResourceController.downloadImportTemplate.method]: {
      summary: '下载视图导入模板',
      method: 'post',
      apiPrefix: true,
      url: (payload) => `/api/lowcode/resources/download/import/template`,
    },
    [LowcodeResourceController.downloadResource.method]: {
      summary: '下载资源',
      method: 'get',
      apiPrefix: true,
      url: (payload) => `/api/lowcode/resources/${payload.id}/actions/download`,
    },
    [LowcodeResourceController.existenceByCode.method]: {
      summary: '校验code是否存在',
      method: 'get',
      apiPrefix: true,
      url: (payload) => `/api/lowcode/resources/exist`,
    },
    [LowcodeResourceController.exportPdf.method]: {
      summary: '导出pdf',
      method: 'post',
      apiPrefix: true,
      url: (payload) => `/api/lowcode/resources/export/pdf`,
    },
    [LowcodeResourceController.exportView.method]: {
      summary: '导出视图excel',
      method: 'post',
      apiPrefix: true,
      url: (payload) => `/api/lowcode/resources/export/view`,
    },
    [LowcodeResourceController.get.method]: {
      summary: '获取低开资源',
      method: 'get',
      apiPrefix: true,
      url: (payload) => `/api/lowcode/resources/${payload.id}`,
    },
    [LowcodeResourceController.getDetails.method]: {
      summary: '获取低开资源详情',
      method: 'get',
      apiPrefix: true,
      url: (payload) => `/api/lowcode/resources/${payload.id}/details`,
    },
    [LowcodeResourceController.getHistory.method]: {
      summary: '获取低开资源历史详情',
      method: 'get',
      apiPrefix: true,
      url: (payload) => `/api/lowcode/resources/${payload.id}/historys/${payload.historyId}`,
    },
    [LowcodeResourceController.getRuntime.method]: {
      summary: '获取低开运行时资源',
      method: 'get',
      apiPrefix: true,
      url: (payload) => `/api/lowcode/resources/${payload.id}/runtimes/${payload.runtimeId}`,
    },
    [LowcodeResourceController.importViewData.method]: {
      summary: '视图数据导入',
      method: 'post',
      apiPrefix: true,
      url: (payload) => `/api/lowcode/resources/actions/import-view-data`,
    },
    [LowcodeResourceController.index.method]: {
      summary: '低开资源索引生成',
      method: 'post',
      apiPrefix: true,
      url: (payload) => `/api/lowcode/resources/${payload.id}/actions/index`,
    },
    [LowcodeResourceController.load.method]: {
      summary: '加载低开资源',
      method: 'post',
      apiPrefix: true,
      url: (payload) => `/api/lowcode/resources/${payload.id}/actions/load`,
    },
    [LowcodeResourceController.printFormWithWordTemplate.method]: {
      summary: '根据模板打印表单',
      method: 'post',
      apiPrefix: true,
      url: (payload) => `/api/lowcode/resources/actions/print-form-with-template`,
    },
    [LowcodeResourceController.queryBIResources.method]: {
      summary: '查询应用下所有BI资源',
      method: 'get',
      apiPrefix: true,
      url: (payload) => `/api/lowcode/resources/actions/query-bi-resources`,
    },
    [LowcodeResourceController.queryHistorys.method]: {
      summary: '获取低开资源历史',
      method: 'get',
      apiPrefix: true,
      url: (payload) => `/api/lowcode/resources/${payload.id}/historys`,
    },
    [LowcodeResourceController.queryResourceFunctionCodes.method]: {
      summary: '获取低开资源绑定的功能码',
      method: 'get',
      apiPrefix: true,
      url: (payload) => `/api/lowcode/resources/${payload.resourceType}/funcodes/${payload.mode}`,
    },
    [LowcodeResourceController.queryRuntimes.method]: {
      summary: '获取低开运行时资源',
      method: 'get',
      apiPrefix: true,
      url: (payload) => `/api/lowcode/resources/${payload.id}/runtimes`,
    },
    [LowcodeResourceController.queryWithPage.method]: {
      summary: '分页查询低开资源',
      method: 'get',
      apiPrefix: true,
      url: (payload) => `/api/lowcode/resources`,
    },
    [LowcodeResourceController.update.method]: {
      summary: '更新低开资源',
      method: 'put',
      apiPrefix: true,
      url: (payload) => `/api/lowcode/resources/${payload.id}`,
    },
    [LowcodeResourceController.updateBasicInfo.method]: {
      summary: '更新低开资源基本信息',
      method: 'put',
      apiPrefix: true,
      url: (payload) => `/api/lowcode/resources/${payload.id}/basic`,
    },
    [LowcodeResourceController.updateContent.method]: {
      summary: '更新低开资源内容',
      method: 'put',
      apiPrefix: true,
      url: (payload) => `/api/lowcode/resources/${payload.id}/content`,
    },
    [LowcodeResourceController.updateContentWithRuntime.method]: {
      summary: '更新低开资源内容，并且携带运行时内容，前端编译时场景',
      method: 'put',
      apiPrefix: true,
      url: (payload) => `/api/lowcode/resources/${payload.id}/actions/content-with-runtime`,
    },
    [LowcodeResourceController.updateResourceGroup.method]: {
      summary: '移动低开资源目录(不传默认移动到根目录-未分组)',
      method: 'put',
      apiPrefix: true,
      url: (payload) => `/api/lowcode/resources/${payload.id}/group`,
    },
    [LowcodeResourceController.uploadResource.method]: {
      summary: '上传资源内容',
      method: 'post',
      apiPrefix: true,
      url: (payload) => `/api/lowcode/resources/actions/upload`,
    },
  },
}
