// This file is automatically generated

// 低开构件包管理

import { LowcodeContributionController } from '@controller'
export default {
  actions: {
    [LowcodeContributionController.clone.method]: {
      summary: '克隆低开构件包',
      method: 'post',
      apiPrefix: true,
      url: (payload) => `/api/lowcode/contributions/${payload.id}/clone`,
    },
    [LowcodeContributionController.create.method]: {
      summary: '创建低开构件包',
      method: 'post',
      apiPrefix: true,
      url: (payload) => `/api/lowcode/contributions`,
    },
    [LowcodeContributionController.delete.method]: {
      summary: '删除低开构件包',
      method: 'delete',
      apiPrefix: true,
      url: (payload) => `/api/lowcode/contributions/${payload.id}`,
    },
    [LowcodeContributionController.existenceByCode.method]: {
      summary: '校验code是否存在',
      method: 'get',
      apiPrefix: true,
      url: (payload) => `/api/lowcode/contributions/exist`,
    },
    [LowcodeContributionController.get.method]: {
      summary: '获取低开构件包',
      method: 'get',
      apiPrefix: true,
      url: (payload) => `/api/lowcode/contributions/${payload.id}`,
    },
    [LowcodeContributionController.load.method]: {
      summary: '加载低开构件包',
      method: 'post',
      apiPrefix: true,
      url: (payload) => `/api/lowcode/contributions/${payload.id}/actions/load`,
    },
    [LowcodeContributionController.queryWithPage.method]: {
      summary: '分页查询低开构件包',
      method: 'get',
      apiPrefix: true,
      url: (payload) => `/api/lowcode/contributions`,
    },
    [LowcodeContributionController.update.method]: {
      summary: '更新低开构件包',
      method: 'put',
      apiPrefix: true,
      url: (payload) => `/api/lowcode/contributions/${payload.id}`,
    },
  },
}
