// This file is automatically generated

// 业务资源管理

import { LowcodeBizResourceController } from '@controller'
export default {
  actions: {
    [LowcodeBizResourceController.queryBizCatalogsByProject.method]: {
      summary: '查询项目下业务目录树',
      method: 'get',
      apiPrefix: true,
      url: (payload) => `/api/lowcode/bizresources/actions/query-bizcatalog-by-project`,
    },
    [LowcodeBizResourceController.queryBizResourcesByCatalog.method]: {
      summary: '查询业务目录下的业务资源列表',
      method: 'get',
      apiPrefix: true,
      url: (payload) => `/api/lowcode/bizresources/actions/query-bizresources-by-catalog`,
    },
    [LowcodeBizResourceController.queryBizResourcesByProjectAndType.method]: {
      summary: '查询项目下某种类型的业务资源列表',
      method: 'get',
      apiPrefix: true,
      url: (payload) => `/api/lowcode/bizresources/actions/query-bizresources-by-project-type`,
    },
  },
}
