// This file is automatically generated

// 低开项目分支管理

import { LowcodeProjectBranchController } from '@controller'
export default {
  actions: {
    [LowcodeProjectBranchController.checkout.method]: {
      summary: '切换分支',
      method: 'get',
      apiPrefix: true,
      url: (payload) => `/api/lowcode/project-branches/actions/${payload.id}/chenckout`,
    },
    [LowcodeProjectBranchController.create.method]: {
      summary: '创建低开项目分支',
      method: 'post',
      apiPrefix: true,
      url: (payload) => `/api/lowcode/project-branches`,
    },
    [LowcodeProjectBranchController.delete.method]: {
      summary: '根据id删除低开项目分支信息(支持批量删除)',
      method: 'delete',
      apiPrefix: true,
      url: (payload) => `/api/lowcode/project-branches`,
    },
    [LowcodeProjectBranchController.deleteByAppName.method]: {
      summary: '根据低开应用名称删除低开项目分支信息',
      method: 'delete',
      apiPrefix: true,
      url: (payload) => `/api/lowcode/project-branches/${payload.appName}`,
    },
    [LowcodeProjectBranchController.existsByName.method]: {
      summary: '校验分支名称是否重复',
      method: 'get',
      apiPrefix: true,
      url: (payload) => `/api/lowcode/project-branches/actions/exist`,
    },
    [LowcodeProjectBranchController.get.method]: {
      summary: '根据id查询项目分支',
      method: 'get',
      apiPrefix: true,
      url: (payload) => `/api/lowcode/project-branches/${payload.id}`,
    },
    [LowcodeProjectBranchController.getAppCurrentBranch.method]: {
      summary: '查询应用当前分支信息',
      method: 'get',
      apiPrefix: true,
      url: (payload) => `/api/lowcode/project-branches/actions/${payload.appName}/current-branch`,
    },
    [LowcodeProjectBranchController.queryWithPage.method]: {
      summary: '分页查询低开项目分支列表',
      method: 'get',
      apiPrefix: true,
      url: (payload) => `/api/lowcode/project-branches`,
    },
    [LowcodeProjectBranchController.updateBasic.method]: {
      summary: '修改低开项目分支-基本信息',
      method: 'put',
      apiPrefix: true,
      url: (payload) => `/api/lowcode/project-branches/${payload.id}/basic`,
    },
  },
}
