// This file is automatically generated

// 报表数据源和应用的关系管理

import { LowcodeBiDatasourceController } from '@controller'
export default {
  actions: {
    [LowcodeBiDatasourceController.create.method]: {
      summary: '新增报表数据源和应用的关系',
      method: 'post',
      apiPrefix: true,
      url: (payload) => `/api/lowcode/bi-datasources`,
    },
    [LowcodeBiDatasourceController.deleteByIds.method]: {
      summary: '按主键集合删除(参数放body)',
      method: 'put',
      apiPrefix: true,
      url: (payload) => `/api/lowcode/bi-datasources/bulk-delete`,
    },
    [LowcodeBiDatasourceController.queryBiDatasources.method]: {
      summary: '分页查询报表数据源和应用的关系列表',
      method: 'get',
      apiPrefix: true,
      url: (payload) => `/api/lowcode/bi-datasources`,
    },
    [LowcodeBiDatasourceController.update.method]: {
      summary: '修改报表数据源和应用的关系',
      method: 'put',
      apiPrefix: true,
      url: (payload) => `/api/lowcode/bi-datasources`,
    },
  },
}
