// This file is automatically generated

// 低开MDM集成服务

import { LowcodeIntegrationMdmController } from '@controller'
export default {
  actions: {
    [LowcodeIntegrationMdmController.approve.method]: {
      summary: '批准数据',
      method: 'post',
      apiPrefix: true,
      url: (payload) => `/api/lowcode/integration/mdm/data-models/${payload.code}/actions/approve`,
    },
    [LowcodeIntegrationMdmController.deprecate.method]: {
      summary: '废弃数据',
      method: 'post',
      apiPrefix: true,
      url: (payload) => `/api/lowcode/integration/mdm/data-models/${payload.code}/actions/deprecate`,
    },
    [LowcodeIntegrationMdmController.disable.method]: {
      summary: '停用数据',
      method: 'post',
      apiPrefix: true,
      url: (payload) => `/api/lowcode/integration/mdm/data-models/${payload.code}/actions/disable`,
    },
    [LowcodeIntegrationMdmController.enable.method]: {
      summary: '启用数据',
      method: 'post',
      apiPrefix: true,
      url: (payload) => `/api/lowcode/integration/mdm/data-models/${payload.code}/actions/enable`,
    },
    [LowcodeIntegrationMdmController.getDataModel.method]: {
      summary: '获取数据模型信息',
      method: 'get',
      apiPrefix: true,
      url: (payload) => `/api/lowcode/integration/mdm/data-models/${payload.code}`,
    },
    [LowcodeIntegrationMdmController.getDictModel.method]: {
      summary: '获取业务字典模型数据',
      method: 'get',
      apiPrefix: true,
      url: (payload) => `/api/lowcode/integration/mdm/dict-models/${payload.code}`,
    },
    [LowcodeIntegrationMdmController.isEnabled.method]: {
      summary: '是否启用',
      method: 'get',
      apiPrefix: true,
      url: (payload) => `/api/lowcode/integration/mdm/actions/enabled`,
    },
    [LowcodeIntegrationMdmController.push.method]: {
      summary: '推送数据',
      method: 'post',
      apiPrefix: true,
      url: (payload) => `/api/lowcode/integration/mdm/data-models/${payload.code}/actions/push`,
    },
    [LowcodeIntegrationMdmController.queryDataModels.method]: {
      summary: '查询MDM数据模型',
      method: 'get',
      apiPrefix: true,
      url: (payload) => `/api/lowcode/integration/mdm/data-models`,
    },
    [LowcodeIntegrationMdmController.queryDictModelsWithPage.method]: {
      summary: '分页查询业务字典类型数据',
      method: 'get',
      apiPrefix: true,
      url: (payload) => `/api/lowcode/integration/mdm/dict-models`,
    },
    [LowcodeIntegrationMdmController.queryDictsWithPage.method]: {
      summary: '分页查询业务字典数据',
      method: 'get',
      apiPrefix: true,
      url: (payload) => `/api/lowcode/integration/mdm/dict-models/${payload.code}/dicts`,
    },
    [LowcodeIntegrationMdmController.reject.method]: {
      summary: '退回数据',
      method: 'post',
      apiPrefix: true,
      url: (payload) => `/api/lowcode/integration/mdm/data-models/${payload.code}/actions/reject`,
    },
    [LowcodeIntegrationMdmController.release.method]: {
      summary: '发布数据',
      method: 'post',
      apiPrefix: true,
      url: (payload) => `/api/lowcode/integration/mdm/data-models/${payload.code}/actions/release`,
    },
    [LowcodeIntegrationMdmController.revise.method]: {
      summary: '修订数据',
      method: 'post',
      apiPrefix: true,
      url: (payload) => `/api/lowcode/integration/mdm/data-models/${payload.code}/actions/revise`,
    },
    [LowcodeIntegrationMdmController.validate.method]: {
      summary: '校验数据',
      method: 'post',
      apiPrefix: true,
      url: (payload) => `/api/lowcode/integration/mdm/data-models/${payload.code}/actions/validate`,
    },
  },
}
